### ISSUE TITLE
GROMACS version 2020.5

### ISSUE THREAD

**Issue by ocampbel** [ubccr/software-layer#102]
Hello, 

I would like to request that GROMACS v2020.5 be installed for use. Here is a link to the page containing installation instructions: https://manual.gromacs.org/2020.5/install-guide/index.html

Thank you.

**Comment by dsajdak** [comment]
@ocampbel We discussed this in our staff meeting and we're not going to be able to install multiple versions of software.  The list of requests for software installations is just too long.  If you want additional help with installing this in your project space, feel free to reply back to your open ticket and we'll help out.
