### ISSUE TITLE
Trilinos with svFSI

### ISSUE THREAD

**Issue by adibantwal** [ubccr/software-layer#103]
Hi,

I am currently using svFSI on CCR and it has been working great.

Now, I need to use svFSI with Trilinos and it would be great if you could build Trlinos with svFSI.
The instructions are provided, if you need them: https://github.com/SimVascular/svFSI 

Thanks for your help,
Aditya

**Comment by tonykew** [comment]
Dear Aditya,
I have got Trilinos version 13.4.1 compiled, but getting svFSI to compile with it
is proving challenging.
Would you ilke Trilinos to be available stand alone if I can't resolve the svFSI
compilation errors?

**Comment by adibantwal** [comment]
Hi Tony,

Yes, I would like Trilinos to be available stand alone if you can't resolve the svFSI
compilation errors. 

Thanks for your help,
Aditya

**Comment by adibantwal** [comment]
PS. This is a set of commands I use to install Trilinos on svFSI on ubuntu. Just attaching incase it may be of any help.

how to install trilinos with svfsi in ubuntu 18.04 / 20.04
sudo apt-get update && sudo apt-get upgrade && sudo apt update 
sudo apt install build-essential flex bison && sudo apt install gcc
sudo apt install gfortran && sudo apt install liblapack-dev
sudo apt install libblas-dev 
sudo apt install libopenmpi-dev 
sudo apt install openmpi-bin
sudo apt-get install trilinos-all-dev
sudo apt install libptscotch-dev
sudo apt remove --purge --auto-remove cmake
sudo apt purge --auto-remove cmake
sudo apt update && \
sudo apt install -y software-properties-common lsb-release && \
sudo apt clean all
wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
sudo apt-add-repository "deb https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main
sudo apt update && sudo apt install kitware-archive-keyring
sudo rm /etc/apt/trusted.gpg.d/kitware.gpg
sudo apt update && sudo apt install cmake
sudo apt install cmake-curses-gui && mkdir svFSI
cd svFSI && git clone https://github.com/SimVascular/svFSI.git
mkdir build && cd build
nano ../../svFSI/svFSI/Code/CMake/SimVascularOptions.cmake
TURN ON TRILINOS
ccmake -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/cmake/Trilinos ../svFSI
make
git clone https://github.com/SimVascular/svFSI-Tests.git && cd svFSI-Tests/04-fluid/02-dye_AD/
ln -s /home/ubuntu/svFSI/build/svFSI-build/bin/svFSI

**Comment by tonykew** [comment]
I'm compiling with an EasyBuild easyconfig file - was having a linking issue that
I have resolved (missing libraries in the link command.)
I'm recompiling Trilinos to run the BASIC tests (hopefully!)  Assuming that goes
well I'll recompile svFSI against this Trilinos build.

**Comment by tonykew** [comment]
so... the tests will not compile - problems with the Tpetra vs. Kokkos execution
space.  I don't think this is a deal breaker though - I believe all the executables
work despite the tests not working! 
I have a test build of svFSI version 2022.09.26 with Trilinos version 13.4.1 completed.
More info to follow...

**Comment by adibantwal** [comment]
Great.. thanks

**Comment by tonykew** [comment]
Dear Aditya,

svFSI with Trilinos has been published.
The original version of svFSI is still (also) available.


```
vortex1$ module spider svfsi
----------------------------------------------------------------------------
  svfsi:
----------------------------------------------------------------------------
    Description:
      A multi-physics finite element solver for patient-specific blood flow
      simulation including fluid-structure interaction and cardiac
      electrophysiology Resources

     Versions:
        svfsi/2022.09.26-Trilinos-13.4.1
        svfsi/2022.09.26
[...]
vortex1$ module spider svfsi/2022.09.26-Trilinos-13.4.1
----------------------------------------------------------------------------
  svfsi: svfsi/2022.09.26-Trilinos-13.4.1
----------------------------------------------------------------------------
    Description:
[...]
    You will need to load all module(s) on any one of the lines below before the "svfsi/2022.09.26-Trilinos-13.4.1" module is available to load.

      gcc/11.2.0  openmpi/4.1.1
[...]
vortex1$ module load gcc/11.2.0 openmpi/4.1.1 svfsi/2022.09.26-Trilinos-13.4.1
vortex1$ 
```

svfsi is in the PATH:

```
vortex1$ which svFSI
/cvmfs/soft.ccr.buffalo.edu/versions/2023.01/easybuild/software/avx512/MPI/gcc/11.2.0/openmpi/4.1.1/svfsi/2022.09.26-Trilinos-13.4.1/SV/bin/svFSI
vortex1$ 
```

and all the Trilinos binaries:

```
vortex1$ ls ${EBROOTTRILINOS}/bin
algebra                    exotxt                  mat2exo
aprepro                    explore                 nas2exo
blot                       fastq                   nem_slice
blot_cps                   fastq_cps               nem_spread
blot_x11                   fastq_x11               numbers
blot_xcps                  fastq_xcps              nvcc_wrapper
conjoin                    gen3d                   pconjoin
cth_pressure_map           genshell                pepu
decomp                     getopt.seacas           perceptX
delete_small_elements.exe  gjoin                   phalanx_create_evaluator.py
ejoin                      grepos                  shell_to_hex
epu                        hpcbind                 skinner
epup                       io_info                 slice
ex1ex2v2                   io_modify               sphgen
ex2ex1v2                   io_shell                stk_balance.exe
exo2mat                    kokkos_launch_compiler  stk_balance_m2n.exe
exodiff                    krino                   stk_block_extractor
exo_format                 mapvar                  txtexo
exomatlab                  mapvar-kd               zellij
vortex1$ 
```

Thanks,
Tony
