### ISSUE TITLE
vmd

### ISSUE THREAD

**Issue by lx19930** [ubccr/software-layer#117]
Hi,
Can you build a vmd for me please?
Thank you so much!
Xing

**Comment by dsajdak** [comment]
VMD has been published to the ccrsoft/2023.01 software release.  It is available as an app in CCR's OnDemand and we recommend it is used that way as the app is configured to launch VMD properly.  For more information about OnDemand please refer to [our documentation](https://docs.ccr.buffalo.edu/en/latest/portals/ood/)
