### ISSUE TITLE
Request to install softwares/modules

### ISSUE THREAD

**Issue by namdeka** [ubccr/software-layer#119]
Please install the following in ccr to the existing modules: 
1. Snippy: https://github.com/tseemann/snippy
2. Roary: https://sanger-pathogens.github.io/Roary/
3. RAxML: https://github.com/amkozlov/raxml-ng
4. Trimmomatic: https://github.com/timflutre/trimmomatic
5. Porechop: https://github.com/rrwick/Porechop

**Comment by dsajdak** [comment]
Hi @namdeka would you please enter separate requests for each different software package?  This way we can share the load among our staff and hopefully get them installed faster for you.  Thanks!

**Comment by namdeka** [comment]
Done. Thank you!

**Comment by tonykew** [comment]
Moved to separate software requests
