### ISSUE TITLE
Launcher Installation

### ISSUE THREAD

**Issue by peter-zhang-chem** [ubccr/software-layer#131]
Launcher is a utility for performing simple, data parallel, high throughput computing (HTC) workflows on clusters, massively parallel processor (MPP) systems, workgroups of computers, and personal machines.

Github Link: https://github.com/TACC/launcher

**Comment by dsajdak** [comment]
@peter-zhang-chem thanks for your request.  We've already determined this is not something we're going to install in our software repository.  Please see #89 for more details

**Comment by peter-zhang-chem** [comment]
Hi Dori,

Ok, thank you. How long do you thinkI can continue using the `module load ccrsoft/legacy` to run some of the scripts we have using that module before it retires? 

And just for my own curiosity, what is the reason behind not including the launcher? 

Thanks!

Peter

**Comment by peter-zhang-chem** [comment]
Ok thank you Dori!
