### ISSUE TITLE
Install BLCA

### ISSUE THREAD

**Issue by edco84** [ubccr/software-layer#139]
Can you please help install the following tool:

https://github.com/qunfengdong/BLCA

Cordially,

Eduardo Cortes

**Comment by dsajdak** [comment]
Hi @edco84 there is no Easybuild recipe available for this software so this would normally go to the bottom of our to-do list.  However, looking at their installation instructions it appears this can just be done in your own project directory as it is a clone of their Github repo.

**Comment by edco84** [comment]
Thanks @dsajdak . I was able to do installation successfully.
