### ISSUE TITLE
Install Blat, CAP3 and Sge

### ISSUE THREAD

**Issue by leiwei-bioinfo** [ubccr/software-layer#145]
BLAT-3.7:
https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/b/BLAT/BLAT-3.7-GCC-11.2.0.eb
 
CAP3:
https://github.com/easybuilders/easybuild-easyconfigs/tree/develop/easybuild/easyconfigs/c/CAP3
 
 
These are available in easybuild. If you need them, please request the install by creating a ticket here: https://github.com/ubccr/software-layer/issues
 
You can also create a ticket for sge, but we have to check if there is a easybuild recipe out there.

**Comment by dsajdak** [comment]
@leiwei-bioinfo please modify this to request only one software package per Github issue.  This allows other users to "like" and comment if they're interested in a package and it allows our staff to share the load of software installations.  Thanks!
