### ISSUE TITLE
install sge

### ISSUE THREAD

**Issue by leiwei-bioinfo** [ubccr/software-layer#148]
to replace the retired "module load sge"

**Comment by tonykew** [comment]
This module will not be built by CCR because Sun Grid Engine is deprecated.

**Comment by leiwei-bioinfo** [comment]
Hi Tony,

Thanks for looking into that! This "sge" has been essential for our work.
If I understand it correctly, it is built based on SLURM. Although it
mimics SGE commands (which allows us to use our previously built pipeline),
it is not actually based on SGE. Is that correct?

Thank you very much,
Lei
