### ISSUE TITLE
fastp

### ISSUE THREAD

**Issue by yolanda-huang** [ubccr/software-layer#160]
https://github.com/OpenGene/fastp

**Comment by tonykew** [comment]
Test build complete - more info to follow

@aebruno ```
 tarball:
/srv/cosmos/mirrors/ccr/software-dev/ccr-2023.01-easybuild-tonykew_fastp-0.23.2-GCC-11.2.0-2024-01-18.100816.tar.gz
built from stock easyconfig 
```

**Comment by tonykew** [comment]
@aebruno - fastp unit test:  https://github.com/ubccr/sanitarium/pull/32

**Comment by aebruno** [comment]
This is all set. ```module load gcc fastp```
