### ISSUE TITLE
checkm and checkm2

### ISSUE THREAD

**Issue by yolanda-huang** [ubccr/software-layer#162]
https://ecogenomics.github.io/CheckM/

https://github.com/chklovski/CheckM2

**Comment by tonykew** [comment]
Test build of CheckM version 1.1.3 complete - more info to follow

@aebruno 
```
tarball:
/srv/cosmos/mirrors/ccr/software-dev/ccr-2023.01-easybuild-tonykew_CheckM-1.1.3-foss-2021b-2024-01-19.155634.tar.gz 

git pull for the easyconfig file:
https://github.com/ubccr/software-layer/pull/188

git pull for the Pavilion test:
https://github.com/ubccr/sanitarium/pull/33

```

**Comment by tonykew** [comment]
CheckM version 1.1.3 has been published to the CCR software stack.

vortex1$ module spider checkm
--------------------------------------------------------------------------------------------------------------------------------------------------------------
  checkm: checkm/1.1.3
--------------------------------------------------------------------------------------------------------------------------------------------------------------
    Description:
      CheckM provides a set of tools for assessing the quality of genomes recovered from isolates, single cells, or metagenomes.


    You will need to load all module(s) on any one of the lines below before the "checkm/1.1.3" module is available to load.

      gcc/11.2.0  openmpi/4.1.1
[...]
vortex1$ module load gcc/11.2.0 openmpi/4.1.1 checkm/1.1.3
vortex1$ 
vortex1$ checkm -h

                ...::: CheckM v1.1.3 :::...

  Lineage-specific marker set:
    tree         -> Place bins in the reference genome tree
    tree_qa      -> Assess phylogenetic markers found in each bin
    lineage_set  -> Infer lineage-specific marker sets for each bin
[...]
vortex1$

**Comment by aebruno** [comment]
CheckM2 is now available. To use run: `module load foss checkm2`
