### ISSUE TITLE
subread

### ISSUE THREAD

**Issue by chen5027** [ubccr/software-layer#199]
This is directed by Dori's email communication with me and please see the thread below.  Short message is that a module for subread is missing and essential for our analyses.  Could you install it?

Thanks,

Dahong

From me: 
"
If "Rsubread/2.10.0" is already active after loading "r-bundle-bioconductor/3.15-R-4.2.0", it should work when I typed featureCounts, but I saw an error message command not found.

I think the reason could be that featureCounts could be either from the module subread or from an R package Rsubread.  So when Rsubread/2.10.0 is loaded, it still cannot be run in shell.  I guess the module subread (not Rsubread) has to be installed, and I will submit a request.
"

From Dori
"
You do not need to run "module load Rsubread/2.10.0" as this is loaded automatically when you load r-bundle-bioconductor/3.15-R-4.2.0.  The information the module spider command shows: "Names marked by a trailing (E) are extensions provided by another module." means this is included in the module referenced in the message.
"

**Comment by dsajdak** [comment]
This is similar to #200 so will close this issue
