### ISSUE TITLE
emacs

### ISSUE THREAD

**Issue by edco84** [ubccr/software-layer#209]
Can you please install emacs (ver >27). I'm having trouble trying to install it using eb; some trouble with the ninja library which seems to be installed within gcccore, but nested within several folders. When attempting to install ninja through eb, it detects that has already been installed in gcccore.
Thanks.

**Comment by dsajdak** [comment]
In case any other users see this:  emacs is already installed but the login environment isn't loading correctly for the interactive jobs.  After you get on the node, if you run 'module --initial_load restore' then you'll be able to use emacs.   You'll need to run separate commands like this:

```
[vortex]:~$ salloc --partition=general-compute --qos=general-compute --nodes=1 --cluster=ub-hpc; srun --export=HOME,TERM --pty /bin/bash --login
[node]:~$ module --initial_load restore
[node]:~$ emacs
```

This shouldn't have to be necessary so we're working on figuring that out.  But for now, you have a work around.  This also affects OnDemand desktops so once you start an OnDemand session, open a terminal and run the module restore command first.

**Comment by dsajdak** [comment]
This issue has been resolved on our systems, including OnDemand desktops.  There is no longer any need to specify srun or the module restore command.  For interactive jobs, this is the correct salloc command format:

```
[vortex]:~$ salloc --partition=general-compute --qos=general-compute --nodes=1 --cluster=ub-hpc
[node]:~$ emacs
```
