### ISSUE TITLE
OPENMM & OPENMMFORCEFIELDS

### ISSUE THREAD

**Issue by alext1202** [ubccr/software-layer#211]
Hi, I was just wondering if we can install openmmforcefields along with the openmm that is already installed through the CCR. This is an installation through openmm that adds more forcefields that may be missing within just the openmm installation. Here is the github link: https://github.com/openmm/openmmforcefields

**Comment by dsajdak** [comment]
@alext1202 I'm not seeing a way to install this outside of a conda environment.  We no longer support Anaconda environments at CCR.  If you'd like to contact the developers and see if there is an alternative installation document, it may be possible to create a python bundle using Easybuild.
