### ISSUE TITLE
aria2

### ISSUE THREAD

**Issue by KasraBorazjani** [ubccr/software-layer#212]
Hi. I tried to build "aria2" on my own, however, given the compiler dependencies, it proved harder than it seemed at first. Could you please build it?

The EB recipe is available, however, the compiler version isn't supported for the available recipe. Dependencies need CppUnit to be built with ('GCCcore', '11.2.0'), and then changing the aria2 recipe to be built with ('GCCcore', '11.2.0'), ('CppUnit', '1.15.1'), ('libxml2', '2.9.10'), and ('SQLite', '3.36'). 

Also, in the testing phase of the installation, I faced some problems which I couldn't resolve which are the main reason I'm asking it here.

Thanks in advance!

**Comment by dsajdak** [comment]
Hi @KasraBorazjani - aria2 has been published to the ccrsoft/2023.01 software environment.  You can find it with 'module spider' like this:

```
[djm29@vortex2:~]$ module spider aria2

----------------------------------------------------------------------------------------------------------------
  aria2: aria2/1.36.0
----------------------------------------------------------------------------------------------------------------
    Description:
      aria2 is a lightweight multi-protocol & multi-source command-line download utility.


    You will need to load all module(s) on any one of the lines below before the "aria2/1.36.0" module is available to load.

      gcccore/11.2.0

    Help:

      Description
      ===========
      aria2 is a lightweight multi-protocol & multi-source command-line download utility.


      More information
      ================
       - Homepage: https://aria2.github.io
```
