### ISSUE TITLE
Stanza (Python)

### ISSUE THREAD

**Issue by RuiPChaves** [ubccr/software-layer#213]
Greetings,
The code I need to run would normally require:

pip install stanza
stanza.download('en')
import glob

I don't think there is any python module with the Stanza package (https://stanfordnlp.github.io/stanza/). Can you help?
Thank you!

**Comment by RuiPChaves** [comment]
PS - I can make do with "import os" instead of "import glob", if that makes any difference.

**Comment by dsajdak** [comment]
@RuiPChaves this requires pytorch 1.3 or greater. We currently have 1.13.1 installed.  So at this time this isn't something we can install for you.  I'll leave this open though and we can revisit it once we release a newer version of pytorch

**Comment by RuiPChaves** [comment]
Thank you. Is there a way for me to use an environment? Conda is not installed either, apparently.

**Comment by dsajdak** [comment]
@RuiPChaves we don't support native Docker but you can convert docker images on your own machine to Singularity images and then use those on our systems.
