### ISSUE TITLE
dorado

### ISSUE THREAD

**Issue by rditter** [ubccr/software-layer#218]
Dorado-0.5.2
https://github.com/nanoporetech/dorado

**Comment by tonykew** [comment]
I am trying to build Dorado, but it is proving very challenging.
...work is ongoing...

**Comment by tonykew** [comment]
Test build of dorado version 0.3.1 complete - more info to follow

**Comment by aebruno** [comment]
dorado v0.3.1 is now available. To use run: `module load foss dorado`
