### ISSUE TITLE
cellranger

### ISSUE THREAD

**Issue by panagiotisc** [ubccr/software-layer#231]
Could you add the Cell Ranger 7.2.0 as module?  It's already in CCR as an extension but we'd prefer to have it as a module since then we can use it directly from bash.
[cellranger](https://www.10xgenomics.com/support/software/cell-ranger/downloads)

**Comment by tonykew** [comment]
Singe CellRanger requres you to accept their software license, could you
please download the software from:

  https://support.10xgenomics.com/single-cell-gene-expression/software/downloads/latest

...then upload the software bundle to a CCR & provide the path to the uploaded bundle.

Thanks,
Tony
