### ISSUE TITLE
DiffBind R library

### ISSUE THREAD

**Issue by anandsharda1** [ubccr/software-layer#234]
Can someone kindly help me install the library DiffBind in R? 

I tried setting up a temporary folder and installing it myself but was unable to install this particular library. 

https://bioconductor.org/packages/release/bioc/html/DiffBind.html

UBCCR U/N apsharda

Thank you!

**Comment by dsajdak** [comment]
@chen5027 @anandsharda1 this module is available in CCR's installation of the R Bioconductor bundle.  To load use:

```
module load gcc/11.2.0  openmpi/4.1.1 r-bundle-bioconductor/3.15-R-4.2.0
R
> library("DiffBind")
...
>>> DiffBind 3.6.5
>
```
