### ISSUE TITLE
gensim (python module)

### ISSUE THREAD

**Issue by chandola** [ubccr/software-layer#236]
Requesting installation of python module gensim - https://pypi.org/project/gensim/ on CCR machines.

**Comment by chandola** [comment]
`eb -S gensim
== found valid index for /cvmfs/soft.ccr.buffalo.edu/versions/2023.01/easybuild/software/Core/easybuild/4.8.1/easybuild/easyconfigs, so using it...
CFGS1=/cvmfs/soft.ccr.buffalo.edu/versions/2023.01/easybuild/software/Core/easybuild/4.8.1/easybuild/easyconfigs
 * $CFGS1/g/gensim/gensim-0.13.2-foss-2016a-Python-2.7.11.eb
 * $CFGS1/g/gensim/gensim-3.8.3-foss-2020b.eb
 * $CFGS1/g/gensim/gensim-3.8.3-intel-2020b.eb
 * $CFGS1/g/gensim/gensim-4.2.0-foss-2021a.eb

Note: 1 matching archived easyconfig(s) found, use --consider-archived-easyconfigs to see them`

**Comment by dsajdak** [comment]
@chandola This has been installed in the ccrsoft/2023.01 software environment.  Make sure to load the dependencies listed prior to loading this module.

```
module spider gensim

----------------------------------------------------------------------------------------------------------------
  gensim: gensim/4.3.2
----------------------------------------------------------------------------------------------------------------
    Description:
      Gensim is a Python library for topic modelling, document indexing and similarity retrieval with large
      corpora.


    You will need to load all module(s) on any one of the lines below before the "gensim/4.3.2" module is available to load.

      gcc/11.2.0  openmpi/4.1.1
     This extension is provided by the following modules. To access the extension you must load one of the following modules. Note that any module names in parentheses show the module location in the software hierarchy.


       gensim/4.3.2 (gcc/11.2.0 openmpi/4.1.1)


    This module provides the following extensions:

       gensim/4.3.2 (E), smart_open/6.0.0 (E)

    Help:

      Description
      ===========
      Gensim is a Python library for topic modelling, document indexing and similarity retrieval with
       large corpora.


      More information
      ================
       - Homepage: https://radimrehurek.com/gensim

```
