### ISSUE TITLE
R package DiffBind

### ISSUE THREAD

**Issue by chen5027** [ubccr/software-layer#246]
Hello, the R package DiffBind is an essential part of my daily analyses but it is not available on CCR hpc now (see screen messages below, no DiffBind).  I tried to install it according to the link below but it was freezing, presumably because I don't have the authority to install it.  Could you install the package at your earliest convenience?  Please be aware that I need DiffBind version 3 and above.

Thanks,

Dahong

https://bioconductor.org/packages/release/bioc/html/DiffBind.html

$ module spider r

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  r: r/4.2.0
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    Description:
      R is a free software environment for statistical computing and graphics.

    Properties:
      Tools for development

     Other possible modules matches:
        ai-benchmark, amber, amrfinderplus, archspec, aria2, armadillo, arpack-ng, arrow, arrow-r, astropy, berkeleygw, bio-searchio-hmmer, biom-format, bioperl, breseq, brie, brotli, ...

    You will need to load all module(s) on any one of the lines below before the "r/4.2.0" module is available to load.

      gcc/11.2.0  openmpi/4.1.1
 
    This module provides the following extensions:

       abc.data/1.0 (E), abc/2.1 (E), abe/3.0.1 (E), abind/1.4-5 (E), acepack/1.4.1 (E), adabag/4.2 (E), ade4/1.7-19 (E), ADGofTest/0.3 (E), admisc/0.26 (E), aggregation/1.0.1 (E), AICcmodavg/2.3-1 (E), akima/0.6-3.3 (E), alabama/2022.4-1 (E), AlgDesign/1.2.0 (E), alluvial/0.1-2 (E), animation/2.7 (E), aod/1.3.2 (E), apcluster/1.4.9 (E), ape/5.6-2 (E), argparse/2.1.5 (E), arm/1.12-2 (E), askpass/1.1 (E), asnipe/1.1.16 (E), assertive.base/0.0-9 (E), assertive.code/0.0-3 (E), assertive.data.uk/0.0-2 (E), assertive.data.us/0.0-2 (E), assertive.data/0.0-3 (E), assertive.datetimes/0.0-3 (E), assertive.files/0.0-2 (E), assertive.matrices/0.0-2 (E), assertive.models/0.0-2 (E), assertive.numbers/0.0-2 (E), assertive.properties/0.0-5 (E), assertive.reflection/0.0-5 (E), assertive.sets/0.0-3 (E), assertive.strings/0.0-3 (E), assertive.types/0.0-3 (E), assertive/0.3-6 (E), assertthat/0.2.1 (E), AUC/0.3.2 (E), audio/0.1-10 (E), aws/2.5-1 (E), awsMethods/1.1-1 (E), backports/1.4.1 (E), bacr/1.0.1 (E), bartMachine/1.2.6 (E), bartMachineJARs/1.1 (E), base (E), base64/2.0 (E), base64enc/0.1-3 (E), BatchJobs/1.9 (E), batchmeans/1.0-4 (E), BayesianTools/0.1.7 (E), BayesLogit/2.1 (E), bayesm/3.1-4 (E), BayesPen/1.0 (E), bayesplot/1.9.0 (E), BB/2019.10-1 (E), BBmisc/1.12 (E), bbmle/1.0.24 (E), BCEE/1.3.0 (E), BDgraph/2.66 (E), bdsmatrix/1.3-4 (E), beanplot/1.3.1 (E), beeswarm/0.4.0 (E), betareg/3.1-4 (E), BH/1.78.0-0 (E), BiasedUrn/1.07 (E), bibtex/0.4.2.3 (E), BIGL/1.6.5 (E), bigmemory.sri/0.1.3 (E), bigmemory/4.5.36 (E), bindr/0.1.1 (E), bindrcpp/0.2.2 (E), bio3d/2.4-3 (E), biom/0.3.12 (E), biomod2/3.5.1 (E), bit/4.0.4 (E), bit64/4.0.5 (E), bitops/1.0-7 (E), blavaan/0.4-1 (E), blob/1.2.3 (E), BMA/3.18.17 (E), bmp/0.3 (E), bnlearn/4.7.1 (E), bold/1.2.0 (E), boot/1.3-28 (E), bootstrap/2019.6 (E), Boruta/7.0.0 (E), brew/1.0-7 (E), brglm/0.7.2 (E), bridgedist/0.1.1 (E), bridgesampling/1.1-2 (E), brio/1.1.3 (E), brms/2.17.0 (E), Brobdingnag/1.2-7 (E), broom.helpers/1.7.0 (E), broom.mixed/0.2.9.4 (E), broom/0.8.0 (E), bslib/0.3.1 (E), bst/0.3-23 (E), cachem/1.0.6 (E), Cairo/1.5-15 (E), calibrate/1.7.7 (E), callr/3.7.0 (E), car/3.0-12 (E), carData/3.0-5 (E), caret/6.0-92 (E), catlearn/0.9.1 (E), caTools/1.18.2 (E), CBPS/0.23 (E), celestial/1.4.6 (E), cellranger/1.1.0 (E), cgdsr/1.3.0 (E), cghFLasso/0.2-1 (E), checkmate/2.1.0 (E), chemometrics/1.4.2 (E), chkptstanr/0.1.1 (E), chron/2.3-56 (E), circlize/0.4.14 (E), circular/0.4-94.1 (E), class/7.3-20 (E), classInt/0.4-3 (E), cli/3.3.0 (E), clipr/0.8.0 (E), clisymbols/1.2.0 (E), clue/0.3-60 (E), cluster/2.1.3 (E), clusterGeneration/1.3.7 (E), clusterRepro/0.9 (E), clustree/0.4.4 (E), clValid/0.7 (E), cmprsk/2.2-11 (E), cNORM/3.0.1 (E), cobalt/4.3.2 (E), cobs/1.3-4 (E), coda/0.19-4 (E), codetools/0.2-18 (E), coin/1.4-2 (E), collapse/1.7.6 (E), colorspace/2.0-3 (E), colourpicker/1.1.1 (E), combinat/0.0-8 (E), ComICS/1.0.4 (E), commonmark/1.8.0 (E), compiler (E), compositions/2.0-4 (E), CompQuadForm/1.4.3 (E), conditionz/0.1.0 (E), conquer/1.3.0 (E), contfrac/1.1-12 (E), copCAR/2.0-4 (E), copula/1.0-1 (E), corpcor/1.6.10 (E), corrplot/0.92 (E), covr/3.5.1 (E), CovSel/1.2.1 (E), covsim/0.2.1 (E), cowplot/1.1.1 (E), coxed/0.3.3 (E), coxme/2.2-16 (E), cpp11/0.4.2 (E), crayon/1.5.1 (E), credentials/1.3.2 (E), crosstalk/1.2.0 (E), crul/1.2.0 (E), cSEM/0.4.0 (E), csSAM/1.2.4 (E), ctmle/0.1.2 (E), cubature/2.0.4.4 (E), cubelyr/1.0.1 (E), curl/4.3.2 (E), cvAUC/1.1.4 (E), CVST/0.2-3 (E), d3Network/0.5.2.1 (E), dagitty/0.3-1 (E), data.table/1.14.2 (E), data.tree/1.0.0 (E), DataCombine/0.2.21 (E), datasets (E), date/1.2-39 (E), dbarts/0.9-22 (E), DBI/1.1.2 (E), dbplyr/2.1.1 (E), dcurver/0.9.2 (E), ddalpha/1.3.13 (E), deal/1.2-39 (E), debugme/1.1.0 (E), deldir/1.0-6 (E), dendextend/1.15.2 (E), DEoptim/2.2-6 (E), DEoptimR/1.0-11 (E), Deriv/4.1.3 (E), desc/1.4.1 (E), DescTools/0.99.44 (E), deSolve/1.32 (E), devtools/2.4.3 (E), dfidx/0.0-4 (E), DHARMa/0.4.5 (E), dHSIC/2.1 (E), diagram/1.6.5 (E), DiagrammeR/1.0.9 (E), DiceKriging/1.6.0 (E), dichromat/2.0-0 (E), diffobj/0.3.5 (E), digest/0.6.29 (E), dimRed/0.2.5 (E), diptest/0.76-0 (E), DiscriMiner/0.1-29 (E), dismo/1.3-5 (E), distillery/1.2-1 (E), distr/2.8.0 (E), distrEx/2.8.0 (E), distributional/0.3.0 (E), DistributionUtils/0.6-0 (E), diveRsity/1.9.90 (E), DMCfun/2.0.2 (E), docstring/1.0.0 (E), doMC/1.3.8 (E), doParallel/1.0.17 (E), doRNG/1.8.2 (E), doSNOW/1.0.20 (E), dotCall64/1.0-1 (E), downloader/0.4 (E), dplyr/1.0.8 (E), dr/3.0.10 (E), drgee/1.1.10 (E), DRR/0.0.4 (E), drugCombo/1.2.1 (E), DT/0.22 (E), dtangle/2.0.9 (E), dtplyr/1.2.1 (E), DTRreg/1.7 (E), dtw/1.22-3 (E), dummies/1.5.6 (E), dygraphs/1.1.1.6 (E), dynamicTreeCut/1.63-1 (E), e1071/1.7-9 (E), earth/5.3.1 (E), EasyABC/1.5 (E), elementR/1.3.7 (E), ellipse/0.4.2 (E), ellipsis/0.3.2 (E), elliptic/1.4-0 (E), emdbook/1.3.12 (E), emulator/1.2-21 (E), energy/1.7-10 (E), ENMeval/2.0.3 (E), entropy/1.3.1 (E), EnvStats/2.7.0 (E), ergm.count/4.0.2 (E), ergm/4.1.2 (E), evaluate/0.15 (E), EValue/4.1.3 (E), evd/2.3-6 (E), Exact/3.1 (E), expm/0.999-6 (E), ExPosition/2.8.23 (E), expsmooth/2.3 (E), extrafont/0.18 (E), extrafontdb/1.0 (E), extRemes/2.1-1 (E), FactoMineR/2.4 (E), FactorCopula/0.8 (E), fail/1.3 (E), fansi/1.0.3 (E), farver/2.1.0 (E), fastcluster/1.2.3 (E), fasterize/1.0.3 (E), fastICA/1.2-3 (E), fastmap/1.1.0 (E), fastmatch/1.1-3 (E), fdrtool/1.2.17 (E), feather/0.3.5 (E), ff/4.0.5 (E), ffbase/0.13.3 (E), fftw/1.0-7 (E), fftwtools/0.9-11 (E), fields/13.3 (E), filehash/2.4-3 (E), finalfit/1.0.4 (E), findpython/1.0.7 (E), fishMod/0.29 (E), fitdistrplus/1.1-8 (E), flashClust/1.01-2 (E), flexclust/1.4-1 (E), flexmix/2.3-17 (E), fma/2.4 (E), FME/1.3.6.2 (E), fmri/1.9.6 (E), FNN/1.1.3 (E), fontawesome/0.2.2 (E), forcats/0.5.1 (E), foreach/1.5.2 (E), forecast/8.16 (E), foreign/0.8-82 (E), formatR/1.12 (E), formula.tools/1.7.1 (E), Formula/1.2-4 (E), fossil/0.4.0 (E), fpc/2.2-9 (E), fpp/0.5 (E), fracdiff/1.5-1 (E), fs/1.5.2 (E), furrr/0.2.3 (E), futile.logger/1.4.3 (E), futile.options/1.0.1 (E), future.apply/1.9.0 (E), future/1.25.0 (E), gam/1.20.1 (E), gamlss.data/6.0-2 (E), gamlss.dist/6.0-3 (E), gamlss.tr/5.1-7 (E), gamlss/5.4-3 (E), gamm4/0.2-6 (E), gap/1.2.3-1 (E), gapfill/0.9.6-1 (E), gargle/1.2.0 (E), gaussquad/1.0-2 (E), gbm/2.1.8 (E), gbRd/0.4-11 (E), gclus/1.3.2 (E), gdalUtils/2.0.3.2 (E), gdata/2.18.0 (E), gdistance/1.3-6 (E), gee/4.13-22 (E), geeM/0.10.1 (E), geepack/1.3.3 (E), geex/1.0.12 (E), geiger/2.0.7 (E), GeneNet/1.2.16 (E), generics/0.1.2 (E), genoPlotR/0.8.11 (E), GenSA/1.1.7 (E), geojsonsf/2.0.2 (E), geometries/0.2.0 (E), geometry/0.4.6 (E), gert/1.6.0 (E), getopt/1.20.3 (E), GetoptLong/1.0.5 (E), GGally/2.1.2 (E), ggbeeswarm/0.6.0 (E), ggdag/0.2.4 (E), ggExtra/0.10.0 (E), ggfan/0.1.3 (E), ggforce/0.3.3 (E), ggnetwork/0.5.10 (E), ggplot2/3.3.5 (E), ggpubr/0.4.0 (E), ggraph/2.0.5 (E), ggrepel/0.9.1 (E), ggridges/0.5.3 (E), ggsci/2.9 (E), ggsignif/0.6.3 (E), ggvis/0.4.7 (E), gh/1.3.0 (E), GillespieSSA/0.6.2 (E), git2r/0.30.1 (E), gitcreds/0.1.1 (E), GJRM/0.2-6 (E), glasso/1.11 (E), gld/2.6.4 (E), gllvm/1.3.1 (E), glmmML/1.1.2 (E), glmmTMB/1.1.3 (E), glmnet/4.1-4 (E), GlobalOptions/0.1.2 (E), globals/0.14.0 (E), glue/1.6.2 (E), gmm/1.6-6 (E), gmodels/2.18.1 (E), gmp/0.6-5 (E), gnumeric/0.7-8 (E), goftest/1.2-3 (E), gomms/1.0 (E), googledrive/2.0.0 (E), googlesheets4/1.0.0 (E), gower/1.0.0 (E), GPArotation/2022.4-1 (E), gplots/3.1.3 (E), graphics (E), graphlayouts/0.8.0 (E), grDevices (E), grf/2.1.0 (E), grid (E), gridBase/0.4-7 (E), gridExtra/2.3 (E), grImport2/0.2-0 (E), grpreg/3.4.0 (E), GSA/1.03.2 (E), gsalib/2.1 (E), gsl/2.1-7.1 (E), gsw/1.0-6 (E), gt/0.5.0 (E), gtable/0.3.0 (E), gtools/3.9.2 (E), gtsummary/1.6.0 (E), GUTS/1.2.3 (E), gWidgets2/1.0-9 (E), gWidgets2tcltk/1.0-8 (E), GxEScanR/2.0.2 (E), h2o/3.36.0.4 (E), hal9001/0.4.3 (E), hardhat/0.2.0 (E), harmony/0.1.0 (E), hash/2.2.6.2 (E), haven/2.5.0 (E), hdf5r/1.3.5 (E), hdm/0.3.1 (E), heatmap3/1.1.9 (E), here/1.0.1 (E), hexbin/1.28.2 (E), HiddenMarkov/1.8-13 (E), highr/0.9 (E), Hmisc/4.7-0 (E), hms/1.1.1 (E), Hmsc/3.0-11 (E), htmlTable/2.4.0 (E), htmltools/0.5.2 (E), htmlwidgets/1.5.4 (E), httpcode/0.3.0 (E), httpuv/1.6.5 (E), httr/1.4.2 (E), huge/1.3.5 (E), hunspell/3.0.1 (E), hwriter/1.3.2.1 (E), HWxtest/1.1.9 (E), hypergeo/1.2-13 (E), ica/1.0-2 (E), IDPmisc/1.1.20 (E), idr/1.2 (E), ids/1.0.1 (E), ie2misc/0.8.8 (E), igraph/1.3.1 (E), image.binarization/0.1.2 (E), imager/0.42.13 (E), imagerExtra/1.3.2 (E), ineq/0.2-13 (E), influenceR/0.1.0.1 (E), infotheo/1.2.0.1 (E), ini/0.3.1 (E), inline/0.3.19 (E), intergraph/2.0-2 (E), interpretR/0.2.4 (E), intrinsicDimension/1.2.0 (E), inum/1.0-4 (E), ipred/0.9-12 (E), irace/3.4.1 (E), irlba/2.3.5 (E), ismev/1.42 (E), Iso/0.0-18.1 (E), isoband/0.2.5 (E), ISOcodes/2022.01.10 (E), iterators/1.0.14 (E), itertools/0.1-3 (E), JADE/2.0-3 (E), janeaustenr/0.1.5 (E), JBTools/0.7.2.9 (E), jiebaR/0.11 (E), jiebaRD/0.1 (E), jomo/2.7-3 (E), jpeg/0.1-9 (E), jquerylib/0.1.4 (E), jsonify/1.2.1 (E), jsonlite/1.8.0 (E), jstable/1.0.7 (E)

**Comment by dsajdak** [comment]
@chen5027 thanks for your request.  This is already an open issue [here](#234) so we'll close this issue.  Please follow that request for updates
