### ISSUE TITLE
install qs package for R

### ISSUE THREAD

**Issue by gy2025** [ubccr/software-layer#248]
Hi,
More and more dataset files are saved using qs in R recently, The dataset in this format can only be read if the R package qs is installed. The link for its installation is here:
https://cran.r-project.org/web/packages/qs/vignettes/vignette.html

If R4.3 is to be installed, I hope this qs package is also included.
Thank you, 
Guojun

**Comment by dsajdak** [comment]
@gy2025 this has been installed under R 4.2 in the `ccrsoft/2023.01` software release.  When we release a new version of R we plan to install all the same packages as have previously been requested, as long as they are compatible.

**Comment by gy2025** [comment]
Hi, Dori, That's great, Thank you for letting me know. Have a great weekend, Guojun
________________________________

**Comment by gy2025** [comment]
Hi, Dorri,
I suddenly had problems when I was using it some minutes ago (still there now): I opened a file with vim, but was unable to save changes. Also the job I submitted just completes in a couple of seconds without any error message in the output file. Not sure it's an issue the system is experiencing or sth I can deal with on my end. Thank you, Guojun

**Comment by dsajdak** [comment]
@gy2025 Please submit a ticket to CCR help about this issue as this Github repo is only for software installation requests and bugs associated with them.  Your issue sounds like you're out of disk space.

**Comment by gy2025** [comment]
It just came back, probably a system glitch. Hope it stays. Thank you, Guojun
________________________________
