### ISSUE TITLE
PyTorch 2.2.1

### ISSUE THREAD

**Issue by puru-soni-04** [ubccr/software-layer#258]
A newer version of PyTorch (with CUDA 11.8 support); required for some newer versions of other dependent packages.

The currently available version is `pytorch/1.13.1-CUDA-11.8.0`

I couldn't find the easybuild recipy by running `eb -S pytorch` for version >=2. 

I also tried installing PyTorch 2.1.1 using pip and it worked, but it is not able to detect the GPU/CUDA. if easybuild doesn't have a recipe, can I get instruction on how to set it up w/ GPU support using pip?

**Comment by dsajdak** [comment]
@puru-soni-04 We provide one version of software packages per software release.  A newer version of pytorch will be available in the next software release, due out later this year.  It is not an easy thing to build GPU-enabled codes so we don't provide instructions for users to attempt this.

**Comment by puru-soni-04** [comment]
Okay, thanks
