### ISSUE TITLE
Ansys HFSS Install

### ISSUE THREAD

**Issue by kyle2002h** [ubccr/software-layer#264]
Would it be possible to install the following:
https://catalog.ansys.com/product/5deea381393ff655a4ef1512/electro-thermal

The electrical engineering department has a license for this product, please contact me if you have any questions.
Thank you

**Comment by dsajdak** [comment]
We are working to containerize this along with the main Ansys installation. The Easybuild recipes don't work well in our environment.  I've marked this on hold as we are first working out the Ansys container.  Once that's done we'll get this one worked out.

**Comment by kyle2002h** [comment]
Hello,

Over the past month I've explored alternatives to using this software for
my project. While this software would be useful I may not be able to
leverage it significantly before I graduate from UB in less than a month.
If you don't foresee this install being needed by anyone else using CCR you
may disregard it as I may not be able to use it enough to make it worth
your trouble.

Best,
Kyle

**Comment by dsajdak** [comment]
@kyle2002h thanks for letting us know that!  We're going to leave this issue open because there are others interested in having it installed.  Congrats on your graduation!
