### ISSUE TITLE
IGV Browser (Desktop or Command line)

### ISSUE THREAD

**Issue by jebard** [ubccr/software-layer#267]
I’m working with Dr. Park on getting the IGV browser tool up and running for the BCH519 class, as well as general use.

This tool is a java based and they offer a Desktop and command line option to run it, but I was having problems yesterday getting it up and running due to some missing system libraries I think? I believe there is also an easy_build for it as well.
  
Tool link: https://igv.org/doc/desktop/

Error i encountered when trying to instal myself:
SEVERE [Mar 14,2024 20:56] [DefaultExceptionHandler] java.lang.UnsatisfiedLinkError: /projects/academic/gbcstaff/utils/IGV_2.17.3/jdk-17.0.10/lib/libawt_xawt.so: libXext.so.6: cannot open shared object file: No such file or directory
                at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
                at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open

Thanks!
Jonathan

**Comment by dsajdak** [comment]
@jebard IGV has been published to the `ccrsoft/2023.01` software repository.  To use the GUIs, you must use an OnDemand desktop app.

```
$ module spider igv

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  igv: igv/2.16.0-Java-11
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    Description:
      This package contains command line utilities for preprocessing, computing feature count density (coverage), sorting, and indexing data files.


    This module can be loaded directly: module load igv/2.16.0-Java-11

    Help:

      Description
      ===========
      This package contains command line utilities for
       preprocessing, computing feature count density (coverage),  sorting, and
       indexing data files.


      More information
      ================
       - Homepage: https://www.broadinstitute.org/software/igv/

$ module load igv/2.16.0-Java-11
$ $EBROOTIGV/igv.sh
$ $EBROOTIGV/igvtools_gui
