### ISSUE TITLE
Building a new software svFSI

### ISSUE THREAD

**Issue by adibantwal** [ubccr/software-layer#27]
Hello!

Just saw the new documentation on CCR and I appreciate it very much. It was a great read through.

I wanted to install a software called svFSI. A full URL for the detailed build instructions are available here: https://github.com/SimVascular/svFSI.

I have experience building this software personally and on AWS but am not quite sure how to approach it on CCR. Hence, I am submitting a request for this software to be built.

Overall,
Thanks a lot for your efforts and help.

Aditya

**Comment by aebruno** [comment]
@adibantwal This module is now available. I tested using the examples [here](https://github.com/SimVascular/svFSI-Tests). For example:

```
$ git clone https://github.com/SimVascular/svFSI-Tests.git
$ cd svFSI-Tests/04-fluid/06-channel-flow-2D
$ module load foss
$ module load svfsi
$ mpiexec -n 2 svFSI ./svFSI_Taylor-Hood.inp
```

Note: svFSI is not currently built with Trilinos support.

**Comment by adibantwal** [comment]
Hello and thank you very much! I will test it out.

**Comment by aebruno** [comment]
Can you confirm you're using the new software modules. See the [docs](https://docs.ccr.buffalo.edu/en/latest/software/modules/)

**Comment by adibantwal** [comment]
I just tested the new software modules and and it is now working perfectly. Thank you!!
