### ISSUE TITLE
BCL Convert

### ISSUE THREAD

**Issue by bjmarzul** [ubccr/software-layer#271]
Could a module be created for bcl-convert? The software and documentation is found here:

https://support.illumina.com/sequencing/sequencing_software/bcl-convert.html

**Comment by dsajdak** [comment]
Hi @bjmarzul though there is an Easybuild recipe for this, it is not installing from source and probably will not work on our systems.  They only have two supported versions and neither match what we're running.  When we can install from source we can almost always make it work.  However, we will give this a try.  Alternatively, you can try running it from a container as you would then have control over the operating system.  We'll update you after trying this install with Easybuild.

**Comment by ashipde** [comment]
I also await a module with this utility. I hope we can get one soon.

**Comment by tonykew** [comment]
I have a module built, which needs to go through internal testing.
I will update here when the module is available for production use.

**Comment by ashipde** [comment]
Thanks. For the time-being I was able to use BCL Convert in [NextFlow demultiplex](https://nf-co.re/demultiplex/1.4.0) with Singularity.

**Comment by aebruno** [comment]
Closing in favor of using singularity
