### ISSUE TITLE
GCTB

### ISSUE THREAD

**Issue by liangshy3** [ubccr/software-layer#273]
Hi,
Could you please install the software GCTB. We use this tool for genome-wide complex trait Bayesian analysis. The **source code** can be found here https://cnsgenomics.com/software/gctb/#Download.

Many thanks,
Shuyi

**Comment by dsajdak** [comment]
@liangshy3 Andre from Roswell is working on a container with this software so it can be used by your group.  He's been in communication with Dr. Zhu about it.
