### ISSUE TITLE
SOUPy

### ISSUE THREAD

**Issue by pratyush977** [ubccr/software-layer#281]
Hi ,
Could you install the software on CCR or give easybuild recipe for the software https://github.com/hippylib/soupy

**Comment by dsajdak** [comment]
Hi @pratyush977 This software has no Easybuild recipe available and so it falls to the bottom of our to-do list.  We currently do not have the staffing levels to work on creating new EB recipes for software such as this.  The installation directions include only instructions for using conda environments, which we do not support at CCR.  Unfortunately, you will have to install this on your own in your group's project directory.
