### ISSUE TITLE
Install GATE 9.4

### ISSUE THREAD

**Issue by rutaoyao** [ubccr/software-layer#296]
Would you please help me to install GATE 9.4?
The link to the instruction page is: http://www.opengatecollaboration.org/ ==> Documentation (tab) => Users Guide & Installation Guide 

![image](https://github.com/ubccr/software-layer/assets/129967981/ad1c5712-b835-4d4e-937b-0c0a2758baa8)
![image](https://github.com/ubccr/software-layer/assets/129967981/ff234153-c205-47bd-8180-a14126e182bf)

Please contact me if you have any questions. My phone number is 716-829-2585.
Thanks!
Rutao

**Comment by tonykew** [comment]
Gate version 9.4 has been published to the ccrsoft/2023.01 software release

To run in text mode:

```
$ module load gcc/11.2.0 openmpi/4.1.1 gate/9.4 geant4-data/11.2
$ Gate
[G4] 
[G4] **************************************************************
[G4]  Geant4 version Name: geant4-11-02-patch-01 [MT]   (16-February-2024)
[...]
[Core-0] You are using Geant4 version 11.2.1
PreInit> 
```

To run the GUI

```
$ module load gcc/11.2.0 openmpi/4.1.1 gate/9.4 geant4-data/11.2
$ LC_NUMERIC=C Gate --qt
```
