### ISSUE TITLE
PLINK

### ISSUE THREAD

**Issue by rmn8** [ubccr/software-layer#307]
Download PLINK from https://www.cog-genomics.org/plink2/
Thanks

**Comment by tonykew** [comment]
PLINK2 version 2.00a2.3 has been built, and is going through internal testing.
I will update this request once PLINK2 has been published.

**Comment by tonykew** [comment]
PLINK2 version 2.00a2.3 segfaults on a simple test.
I have build version 2.00a3.7 - internal testing continues...
I will update this request once PLINK2 has been published.
