### ISSUE TITLE
Download libgfortran libarary

### ISSUE THREAD

**Issue by rmn8** [ubccr/software-layer#318]
The download instruction is in https://stackoverflow.com/questions/62908955/how-to-install-libgfortran-so-3-on-ubuntu-20-04

**Comment by aebruno** [comment]
This is already available: `module load gcc`

**Comment by rmn8** [comment]
Hi I tried using it using module load gcc but it seems to  not work
I tried module spider libgfortran but that seems to not show any result

**Comment by aebruno** [comment]
@rmn8 If you're having issues feel free to submit a help ticket.
