### ISSUE TITLE
Tensorflow-Federated Package

### ISSUE THREAD

**Issue by Abhidragneel** [ubccr/software-layer#32]
I, Abhijith G. Anil, (CCR Username: abhijit3) am currently working with Dr. Haimonti Dutta on a Federated Learning project which requires the TensorFlow-Federated package, currently unavailable on the CCR. Hence I request access to said package.

**Comment by Abhidragneel** [comment]
https://github.com/tensorflow/federated/blob/main/docs/install.md

**Comment by aebruno** [comment]
Tensorflow is now available. Unfortunately, we will not be building the federated version.
