### ISSUE TITLE
einops python package

### ISSUE THREAD

**Issue by scottdoy** [ubccr/software-layer#328]
The `einops` python package provides tensor rearranging code, very helpful for quick and complex data manipulation in Pytorch and other related modules.

Software github: https://github.com/arogozhnikov/einops
There is an easyconfig recipe for version 0.7.0 here: https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/e/einops/einops-0.7.0-GCCcore-12.3.0.eb

I was not able to get this recipe work in our research group, the toolchain was not compatible between the pip dependencies and the python version. 

Thank you!

**Comment by tonykew** [comment]
einops version 0.7.0 has been published to the ccrsoft/2023.01 software release.

```
login1$ module spider einops
----------------------------------------------------------------------------
  einops: einops/0.7.0
----------------------------------------------------------------------------
    Description:
      Flexible and powerful tensor operations for readable and reliable
      code. Supports numpy, pytorch, tensorflow, jax, and others.


    You will need to load all module(s) on any one of the lines below before the "einops/0.7.0" module is available to load.

      gcccore/11.2.0
[...]
login1$ module load gcccore/11.2.0 einops/0.7.0
login1$ 
```

The python module here:

```
login1$ ls ${EBROOTEINOPS}/lib/python3.9/site-packages
einops  einops-0.7.0.dist-info
login1$ 
```

is added to the PYTHONPATH when the module is loaded:

```
login1$ echo ${PYTHONPATH} | grep ${EBROOTEINOPS}/lib/python3.9/site-packages
/cvmfs/soft.ccr.buffalo.edu/versions/2023.01/easybuild/software/avx512/Compiler/gcccore/11.2.0/einops/0.7.0/lib/python3.9/site-packages:/cvmfs/soft.ccr.buffalo.edu/versions/2023.01/easybuild/software/avx512/Compiler/gcccore/11.2.0/python/3.9.6/easybuild/python
login1$ 
```
