### ISSUE TITLE
Python 3.5 installation

### ISSUE THREAD

**Issue by frghmah** [ubccr/software-layer#339]
Hello,

I am writing to request the installation of **Python 3.5** in my personal directory on CCR. I would appreciate it if you could install it. I need this version to set up a virtual environment for Python 3.5 in order to install TensorFlow 1.4 and NumPy 1.15.

Thank you,

**Comment by tonykew** [comment]
We don't install software into a personal directory - it is highly likely you
will run out of home directory quota if you do - install software into a
/projects directory.

Python 3.5 is not the most recent version of Python

Within the current ccrsoft/2023.01 software release you can module load
Python version 3.9.6

```
login1$ module load gcc/11.2.0 python/3.9.6
login1$ python --version
Python 3.9.6
login1$ 
```

We have a newer version of TensorFlow installed that will work with our GPUs:

```
login1$ module load gcc/11.2.0 openmpi/4.1.1 tensorflow/2.11.0-CUDA-11.8.0
login1$ ls ${EBROOTTENSORFLOW}/bin
estimator_ckpt_converter  __pycache__     pyrsa-sign       tensorboard
google-oauthlib-tool      pyrsa-decrypt   pyrsa-verify     tflite_convert
import_pb_to_tensorboard  pyrsa-encrypt   pythran          tf_upgrade_v2
markdown_py               pyrsa-keygen    pythran-config   toco
portserver.py             pyrsa-priv2pub  saved_model_cli  toco_from_protos
login1$ 
login1$ tensorboard --help
2024-06-18 17:46:36.842186: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX512_VNNI
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-06-18 17:46:37.085564: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
usage: tensorboard [-h] [--helpfull] [--logdir PATH] [--logdir_spec PATH_SPEC]
                   [--host ADDR] [--bind_all] [--port PORT]
                   [--reuse_port BOOL] [--load_fast {false,auto,true}]
                   [--extra_data_server_flags EXTRA_DATA_SERVER_FLAGS]
                   [--grpc_creds_type {local,ssl,ssl_dev}]
[...]
$ 
```

This TensorFlow module includes scipy-bundle/2021.10 which in turn includes
numpy/1.21.3 so this has all you need.

**Comment by frghmah** [comment]
Thank you for the reply. My issue is that the Python code I need to run was originally written for TensorFlow version 1. The following versions of Python and packages are required for the code:

Python 3.5
TensorFlow 1.4
NumPy 1.15
Is there any way to create a virtual environment for Python 3.5 and install the required packages?
