### ISSUE TITLE
Older version of Python and packages

### ISSUE THREAD

**Issue by frghmah** [ubccr/software-layer#341]
Dear Team, 

I need to run some Python code that has been written using the following older versions of Python and packages:

Python 3.5
TensorFlow 1.4
NumPy 1.15
I understand that these are not the most recent versions, but their compatibility is crucial for running the code, which was written for TensorFlow version 1 (specifically 1.4 in my case).

Thank you for your assistance.

**Comment by aebruno** [comment]
Suggest using one of the NGC containers for older versions of TensorFlow. See [here](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/tensorflow) and [here](https://docs.ccr.buffalo.edu/en/latest/howto/containerization/#gpu-enabled-containers). We will not be building/supporting the older python versions you listed but the container approach should work well for your use case.
