### ISSUE TITLE
juicer

### ISSUE THREAD

**Issue by jonnyPizza** [ubccr/software-layer#348]
This softwares is used by many bioinformatic groups here at UB. Used mostly for genome assembly. Please install the following softwares:

https://github.com/aidenlab/juicer

Thank you very much

**Comment by dsajdak** [comment]
@jonnyPizza This does not have an Easybuild recipe so we can not commit to installing it at this time.  However, it should be very easy for you to install in your group's project directory following their instructions [here](https://github.com/aidenlab/juicer/wiki/Installation).
