### ISSUE TITLE
dakota update+queso

### ISSUE THREAD

**Issue by ajbecerr** [ubccr/software-layer#351]
As discussed with Matt Jones, this is a formal record of a build request submission:

- easy-building the latest (dakota 6.20)
- include queso
- run with BLAS, BOOST, and GSL enabled

The "legacy" build from source is archived under the renamed dir: 
/projects/academic/danialfa/software/dakotaLEGACY/

And, the following legacy paths / variables might be relevant / helpful:
$DAK_SRC=/projects/academic/danialfa/software/dakotaLEGACY/dakota_source/
$DAK_BUILD=/projects/academic/danialfa/software/dakotaLEGACY/dakota_build/
$DAK_DEP=/projects/academic/danialfa/software/dakotaLEGACY/dependencies/
$BOOST_ROOT=$DAK_DEP/boost/1.49/
$BOOST_INCLUDE_DIR=$BOOST_ROOT/include/
$BOOST_LIB_DIR=$BOOST_ROOT/lib/
$GSL_CONFIG=$DAK_DEP/gsl/bin/gsl-config

While DAKOTA's unit tests may not check QUESO, we have "simpler" scripts that could check if working!

**Comment by dsajdak** [comment]
@ajbecerr I apologize that this issue wasn't updated but the software you requested is installed.  Please use version 6.20:

```
module spider dakota/6.20.0

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  dakota: dakota/6.20.0
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    Description:
      The Dakota project delivers both state-of-the-art research and robust, usable software for optimization and UQ. Broadly, the Dakota software's advanced parametric analyses enable design exploration, model calibration, risk analysis,
      and quantification of margins and uncertainty with computational models.

    Properties:
      Tools for development

    You will need to load all module(s) on any one of the lines below before the "dakota/6.20.0" module is available to load.

      gcc/11.2.0  openmpi/4.1.1

    Help:

      Description
      ===========
      The Dakota project delivers both state-of-the-art research and robust, usable
       software for optimization and UQ. Broadly, the Dakota software's advanced
       parametric analyses enable design exploration, model calibration, risk
       analysis, and quantification of margins and uncertainty with computational
       models.


      More information
      ================
       - Homepage: https://dakota.sandia.gov/
```
