### ISSUE TITLE
Astral

### ISSUE THREAD

**Issue by kimlu1998** [ubccr/software-layer#353]
Please install this module, Aster, found at https://github.com/chaoszhang/ASTER. It is an updated version of the original software, called Astral.

**Comment by dsajdak** [comment]
@kimlu1998 This software does not have an Easybuild recipe so we can't commit to installing it at this time.  However, this should be easy for you to install in your group's project directory.  Follow their guidance for Linux installations [here](https://github.com/chaoszhang/ASTER?tab=readme-ov-file#for-linuxunixwsl-users).  Once cloned, and in the ASTER directory, run the `make` command.  Once completed, the executable files will be in the `bin` directory.
