### ISSUE TITLE
MotionBERT

### ISSUE THREAD

**Issue by aanexplus** [ubccr/software-layer#361]
Please help with installing MotionBERT: https://github.com/Walter0807/MotionBERT

MotionBERT is a state-of-art tool to convert 2D poses into 3D poses. 

Thank you

**Comment by dsajdak** [comment]
@aanexplus The repo's instructions only provide information for installing using conda which we do not support at CCR.  You can view the requirements.txt file in the repo to get the list of packages it requires and use either a virtual environment to install them or create an Easybuild Python bundle.  We have more information in our Python documentation [here](https://docs.ccr.buffalo.edu/en/latest/howto/python/).  If you decide to use an Easybuild Python bundle, I highly recommend going through our [Easybuild "How To" example](https://docs.ccr.buffalo.edu/en/latest/howto/easybuild/) to learn more about Easybuild first.

**Comment by aanexplus** [comment]
Thank you @dsajdak. I saw the examples on CCR and I have some questions. So if I create a virtual environment, do I need to install pytorch or does that come pre-install with the virtual environment?

**Comment by dsajdak** [comment]
@aanexplus You should not install pytorch in your virtual environment but instead use the one CCR provides in its software environment:

```
 module spider pytorch

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  pytorch: pytorch/1.13.1-CUDA-11.8.0
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    Description:
      Tensors and Dynamic neural networks in Python with strong GPU acceleration. PyTorch is a deep learning framework that puts Python first.


     Other possible modules matches:
        facenet-pytorch, pytorch-geometric, pytorch-lightning

    You will need to load all module(s) on any one of the lines below before the "pytorch/1.13.1-CUDA-11.8.0" module is available to load.

      gcc/11.2.0  openmpi/4.1.1

    Help:

      Description
      ===========
      Tensors and Dynamic neural networks in Python with strong GPU acceleration.
      PyTorch is a deep learning framework that puts Python first.


      More information
      ================
       - Homepage: https://pytorch.org/


----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  To find other possible module matches execute:

      $ module -r spider '.*pytorch.*'
```

If you have any other questions or run into any problems, please submit a ticket to CCR Help.  Thanks!
