### ISSUE TITLE
Install for quicktree and mash tree

### ISSUE THREAD

**Issue by cpahearn** [ubccr/software-layer#362]
Hello,

I would like to install quicktree (https://github.com/khowe/quicktree) (latest quicktree 2.5: https://github.com/khowe/quicktree/releases/tag/v2.5) and mashtree (https://github.com/lskatz/mashtree) (latest mashtree v1.4.6: https://github.com/lskatz/mashtree/releases/tag/v1.4.6).

For quicktree I downloaded the the zip folder, used make, but got an error about not having permission to download the apt. 

Can you provide me with guidance as to how I should download these two programs?

Thank you, 

-Christian

**Comment by dsajdak** [comment]
@cpahearn Please submit this as a ticket to CCR help as this repo is only for software build requests.  Please include the steps you took and the exact error you saw.

Thanks!
