### ISSUE TITLE
Download R version 4.4

### ISSUE THREAD

**Issue by rmn8** [ubccr/software-layer#370]
Hi, 
Currently I am able to load R using 
module load gcc/11.2.0  openmpi/4.1.1 r/4.2.0

But I want to use r/4.4.0
Thanks

**Comment by dsajdak** [comment]
@rmn8 You could install a different version of R using [Easybuild ](https://docs.ccr.buffalo.edu/en/latest/howto/easybuild/)or what might be easier would be to use a Singularity image.  You can find more information about that here: https://rocker-project.org/use/singularity.html

CCR's container documentation can be found [here](https://docs.ccr.buffalo.edu/en/latest/howto/containerization/).
