### ISSUE TITLE
Install GimmeMotifs

### ISSUE THREAD

**Issue by mhalfon** [ubccr/software-layer#371]
I'd like to request installation of GimmeMotifs (bioinformatics software). The home page for the software is here:
https://github.com/vanheeringen-lab/gimmemotifs

EasyBuild recipe is here:
https://docs.easybuild.io/version-specific/supported-software/#gimmemotifs

Comments about using on a cluster are here:
https://gimmemotifs.readthedocs.io/en/master/overview.html#running-on-a-cluster

Thank you!

**Comment by dsajdak** [comment]
@mhalfon GimmeMotifs is installed in the `ccrsoft/2023.01` software environment:

```
login2:~$ ml spider gimme

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  gimmemotifs: gimmemotifs/0.17.2
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    Description:
      Suite of motif tools, including a motif prediction pipeline for ChIP-seq experiments


    You will need to load all module(s) on any one of the lines below before the "gimmemotifs/0.17.2" module is available to load.

      gcc/11.2.0  openmpi/4.1.1
     This extension is provided by the following modules. To access the extension you must load one of the following modules. Note that any module names in parentheses show the module location in the software hierarchy.


       gimmemotifs/0.17.2 (gcc/11.2.0 openmpi/4.1.1)


    This module provides the following extensions:

       biofluff/3.0.4 (E), diskcache/5.4.0 (E), feather-format/0.4.1 (E), gimmemotifs/0.17.2 (E), iteround/1.0.4 (E), logomaker/0.8 (E), loguru/0.6.0 (E), palettable/3.3.0 (E), pybedtools/0.10.0 (E), xdg/6.0.0 (E), xxhash/3.2.0 (E)

    Help:

      Description
      ===========
      Suite of motif tools, including a motif prediction pipeline for ChIP-seq experiments


      More information
      ================
       - Homepage: https://github.com/vanheeringen-lab/gimmemotifs


      Included extensions
      ===================
      biofluff-3.0.4, diskcache-5.4.0, feather-format-0.4.1, gimmemotifs-0.17.2,
      iteround-1.0.4, logomaker-0.8, loguru-0.6.0, palettable-3.3.0,
      pybedtools-0.10.0, xdg-6.0.0, xxhash-3.2.0


Names marked by a trailing (E) are extensions provided by another module.

gimme motifs -h
usage: gimme [-h] <subcommand> [options] motifs [-h] [-b BACKGROUND] [-g GENOME] [--denovo] [--known] [--noreport] [--rawscore] [--nogc] [-N INT] [-p PFMFILE] [-t N] [-a ANALYSIS] [-k] [-S] [-f FRACTION] [-s N] INPUT OUTDIR

positional arguments:
  INPUT                 FASTA, BED, narrowPeak or region file.
  OUTDIR                Output directory.

optional arguments:
  -h, --help            show this help message and exit
  -b BACKGROUND, --background BACKGROUND
                        Background type (random,genomic,gc,promoter,custom) or a file with background sequences (FASTA, BED or regions)
  -g GENOME             Genome name or fasta file
  --denovo              Only use de novo motifs
  --known               Only use known motifs
  --noreport            Don't create a HTML report.
  --rawscore            Don't z-score normalize motif scores
  --nogc                Don't use GC% bins
  -N INT, --nthreads INT
                        Number of threads (default 12)

optional arguments for known motifs:
  -p PFMFILE            PFM file with motifs.(default: gimme.vertebrate.v5.0.pfm)

optional arguments for de novo motifs:
  -t N, --tools N       Tools to use, any combination of AMD,BioProspector,ChIPMunk,HMS,Improbizer,MDmodule,MotifSampler,Posmo (default BioProspector,Homer,MEME)
  -a ANALYSIS, --analysis ANALYSIS
                        Analysis type: small, medium, large, xl (xl)
  -k, --keepintermediate
                        Don't delete intermediate files
  -S, --singlestrand    Only predict motifs for single + strand (default is both)
  -f FRACTION, --fraction FRACTION
                        Fraction of peaks to use for motif predicton (0.2)
  -s N, --size N        Region size to use for motif prediction (200). Set to 0 to use the size of the input regions.
```

**Comment by mhalfon** [comment]
Thanks Dori.
m

> On Sep 30, 2024, at 3:15 PM, Dori Sajdak ***@***.***> wrote:
> 
> 
> @mhalfon GimmeMotifs is installed in the ccrsoft/2023.01 software environment:
> 
> login2:~$ ml spider gimme
> 
> -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
>   gimmemotifs: gimmemotifs/0.17.2
> -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
>     Description:
>       Suite of motif tools, including a motif prediction pipeline for ChIP-seq experiments
> 
> 
>     You will need to load all module(s) on any one of the lines below before the "gimmemotifs/0.17.2" module is available to load.
> 
>       gcc/11.2.0  openmpi/4.1.1
>      This extension is provided by the following modules. To access the extension you must load one of the following modules. Note that any module names in parentheses show the module location in the software hierarchy.
> 
> 
>        gimmemotifs/0.17.2 (gcc/11.2.0 openmpi/4.1.1)
> 
> 
>     This module provides the following extensions:
> 
>        biofluff/3.0.4 (E), diskcache/5.4.0 (E), feather-format/0.4.1 (E), gimmemotifs/0.17.2 (E), iteround/1.0.4 (E), logomaker/0.8 (E), loguru/0.6.0 (E), palettable/3.3.0 (E), pybedtools/0.10.0 (E), xdg/6.0.0 (E), xxhash/3.2.0 (E)
> 
>     Help:
> 
>       Description
>       ===========
>       Suite of motif tools, including a motif prediction pipeline for ChIP-seq experiments
> 
> 
>       More information
>       ================
>        - Homepage: https://github.com/vanheeringen-lab/gimmemotifs
> 
> 
>       Included extensions
>       ===================
>       biofluff-3.0.4, diskcache-5.4.0, feather-format-0.4.1, gimmemotifs-0.17.2,
>       iteround-1.0.4, logomaker-0.8, loguru-0.6.0, palettable-3.3.0,
>       pybedtools-0.10.0, xdg-6.0.0, xxhash-3.2.0
> 
> 
> Names marked by a trailing (E) are extensions provided by another module.
> 
> gimme motifs -h
> usage: gimme [-h] <subcommand> [options] motifs [-h] [-b BACKGROUND] [-g GENOME] [--denovo] [--known] [--noreport] [--rawscore] [--nogc] [-N INT] [-p PFMFILE] [-t N] [-a ANALYSIS] [-k] [-S] [-f FRACTION] [-s N] INPUT OUTDIR
> 
> positional arguments:
>   INPUT                 FASTA, BED, narrowPeak or region file.
>   OUTDIR                Output directory.
> 
> optional arguments:
>   -h, --help            show this help message and exit
>   -b BACKGROUND, --background BACKGROUND
>                         Background type (random,genomic,gc,promoter,custom) or a file with background sequences (FASTA, BED or regions)
>   -g GENOME             Genome name or fasta file
>   --denovo              Only use de novo motifs
>   --known               Only use known motifs
>   --noreport            Don't create a HTML report.
>   --rawscore            Don't z-score normalize motif scores
>   --nogc                Don't use GC% bins
>   -N INT, --nthreads INT
>                         Number of threads (default 12)
> 
> optional arguments for known motifs:
>   -p PFMFILE            PFM file with motifs.(default: gimme.vertebrate.v5.0.pfm)
> 
> optional arguments for de novo motifs:
>   -t N, --tools N       Tools to use, any combination of AMD,BioProspector,ChIPMunk,HMS,Improbizer,MDmodule,MotifSampler,Posmo (default BioProspector,Homer,MEME)
>   -a ANALYSIS, --analysis ANALYSIS
>                         Analysis type: small, medium, large, xl (xl)
>   -k, --keepintermediate
>                         Don't delete intermediate files
>   -S, --singlestrand    Only predict motifs for single + strand (default is both)
>   -f FRACTION, --fraction FRACTION
>                         Fraction of peaks to use for motif predicton (0.2)
>   -s N, --size N        Region size to use for motif prediction (200). Set to 0 to use the size of the input regions.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.
> 

-----------------------------------
Marc S. Halfon, Ph.D.
Professor
Dept. of Biochemistry
Dept. of Biological Sciences
Dept. of Biomedical Informatics
Program in Genetics, Genomics & Bioinformatics
University at Buffalo-SUNY

Room 5128
JSMBS, 955 Main St.
ph: (716) 829-3126
fax: (716) 849-6655
***@***.***
URL: http://halfonlab.ccr.buffalo.edu

mailing address:
Jacobs School of Medicine and Biomedical Sciences
University at Buffalo
955 Main St. 
Buffalo, NY 14203
