### ISSUE TITLE
Cell Ranger ATAC and Cell Ranger Arc 

### ISSUE THREAD

**Issue by ecoger** [ubccr/software-layer#372]
Would it be possible to install Cell Ranger ATAC (https://support.10xgenomics.com/single-cell-atac/software/downloads/latest) and Cell Ranger Arc (https://www.10xgenomics.com/support/software/cell-ranger-arc/downloads)

**Comment by dsajdak** [comment]
@ecoger when we went to look into this build request we found that it requires the user to register and agree to their license agreement.  CCR staff can't do this on behalf of users so these tools will need to be installed in your group's project directory.  Looking at the EB recipes, I think this will be pretty easy for you.  You will only  need to change the version of the software (both in the recipe and in the name of the recipe and change the checksum value which you can get using the `sha256sum` command on our systems.  You can find the EB recipe for CellRanger-ATAC [here ](https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/c/CellRanger-ATAC/CellRanger-ATAC-2.1.0.eb)and CellRanger-ARC [here](https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/c/CellRanger-ARC/CellRanger-ARC-2.0.2.eb).  In case you have not yet used Easybuild, we have documentation [here](https://docs.ccr.buffalo.edu/en/latest/software/modules/) and [here](https://docs.ccr.buffalo.edu/en/latest/software/building/) and a "how to" set of examples [here](https://docs.ccr.buffalo.edu/en/latest/howto/easybuild/).  If you run into any trouble during the installation, please submit a ticket to [ccr-help](https://www.buffalo.edu/ccr/support.html) and we'll help you through it.
