### ISSUE TITLE
MFIX

### ISSUE THREAD

**Issue by BKeim-UB** [ubccr/software-layer#375]
Hi, 

I would like to request that the latest version of MFIX be installed. The software can be found at: 
https://mfix.netl.doe.gov/products/mfix/download/

With additional information on installation without anaconda available [here](https://mfix.netl.doe.gov/doc/mfix/24.2/html/solver/build-source.html)

**Comment by dsajdak** [comment]
Hi @BKeim-UB To access this software the user must register and agree to a license agreement.  CCR staff are not able to do this on behalf of our users so anything that requires this must be installed by users in their project directory.
