### ISSUE TITLE
Install Ghostknockoff

### ISSUE THREAD

**Issue by rmn8** [ubccr/software-layer#381]
Hi, 
I'd like to install GhostKnockoff
below is the link 
https://github.com/conda-forge/r-ghostknockoff-feedstock
https://cran.r-project.org/web/packages/GhostKnockoff/index.html

Thanks

**Comment by dsajdak** [comment]
@rmn8 we recommend you install this R library in your own environment following [these guidelines](https://docs.ccr.buffalo.edu/en/latest/software/modules/#r).  If you run into any trouble with this, please submit a CCR Help ticket.
