### ISSUE TITLE
ILOG CPLEX Optimization Studio

### ISSUE THREAD

**Issue by yangle293** [ubccr/software-layer#388]
Hello,

Please install IBM ILOG CPLEX optimization studio, better with 12.9 and the newest version both. You can find the download link in the website is https://academic.ibm.com/a2mt/downloads/data_science#/. It need an academic registration to use it freely. Thanks!

**Comment by dsajdak** [comment]
Per our policies, anything that requires agreeing to a license, even if it's free, must be installed in the research group's shared project directory.  For anyone else seeing this in the future, there is an existing [Easybuild recipe](https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/c/CPLEX/CPLEX-22.1.1-GCCcore-11.2.0.eb) that can be used that is compatible with CCR's current ccrsoft/2023.01 software environment.
