### ISSUE TITLE
apeglm (build request)

### ISSUE THREAD

**Issue by shinysyk** [ubccr/software-layer#39]
Hi. My name is Yungki Park, and I teach BCH519. I would like to request the installation of apeglm (an R package), which is widely used for RNA-seq analysis. I need it for the class. Thanks for your support!

apeglm: https://bioconductor.org/packages/release/bioc/html/apeglm.html

**Comment by dsajdak** [comment]
@shinysyk we will install this but can't give an estimate for when it will be completed.  We are working on another large project at the moment.  We can't commit to completing this prior to the end of the semester.

**Comment by shinysyk** [comment]
Hi Dori,

Thanks for your reply. I understand your situation. Please install it when
you have time.

Best,
Yungki
