### ISSUE TITLE
STAR-Fusion requires Perl 5.26.0 or Perl 5.28.0

### ISSUE THREAD

**Issue by gy2025** [ubccr/software-layer#399]
Hi, 
I'm using STAR-Fusion, but the latest version is not compatible with our available version of perl 5.34.0 or 5.34.1. It requires Perl 5.26.0 or Perl 5.28.0. it's great if we can have such options because often softwares were made with earlier versions. Thank you very much, Guojun

**Comment by gy2025** [comment]
Though I found an alternative solution using a local installation, but it will be great if the STAR-Fusion can be made available. Thank you, Guojun

**Comment by gy2025** [comment]
Hi, Dori,
I was trying to submit a job that runs the module star. It loads star/2.7.9a in the script, but it failed to load the module with error:
Lmod has detected the following error: The following module(s) are unknown:
"star/2.7.9a"
I used the script before and it was working well. I tried to load the module at the login node, it does load fine. I tried a number of times with the submitted job in the past two days, sometimes I get an error like: inactive module star/2.7.9a, it just didn't load. I also tried to load star/2.7.11b, did not work either.
Please advise.
Thank you, Guojun
________________________________

**Comment by dsajdak** [comment]
@gy2025 Please submit a ticket to [CCR Help](https://docs.ccr.buffalo.edu/en/latest/help/) about this problem.  This Github repo is only to request software installations.  Thanks!
