### ISSUE TITLE
OpenMM 8.0

### ISSUE THREAD

**Issue by tienhungf91** [ubccr/software-layer#40]
Hello, I see OpenMM is available on CCR, but only with version 7.1. The new version 8.0 is now available which supports many new features and has better performance. Could you please install 8.0 alongside 7.1? I see an easybuild for 8.0 here:
https://github.com/easybuilders/easybuild-easyconfigs/tree/develop/easybuild/easyconfigs/o/OpenMM
Thank you very much!

**Comment by dsajdak** [comment]
Hi @tienhungf91!  Thanks for your request.  The newest version of OpenMM for the FOSS toolchain we run at CCR (2021b) is 7.5.1 so that is the only version we can install.  Is this acceptable?  Eventually a newer version will be available in EasyBuild so we can wait for that too.

**Comment by tienhungf91** [comment]
Thank you @dsajdak! Yes, I think the features we want are there in 7.5.1. If you could install it, that'd be great!

**Comment by dsajdak** [comment]
To be installed with CUDA support once @aebruno is done building out the new CUDA modules

**Comment by aebruno** [comment]
@tienhungf91 OpenMM 8.0 is now available: `module load foss openmm/8.0.0-CUDA-11.8.0`
