### ISSUE TITLE
Cogent

### ISSUE THREAD

**Issue by chen5027** [ubccr/software-layer#404]
Hello, we need this software of analyze our RNA-seq data.  Could you install it as a module by following their easy instructions?  There is a Quick Start link on the website below.

Thanks,

Dahong

https://www.takarabio.com/products/next-generation-sequencing/bioinformatics-tools/cogent-ngs-analysis-pipeline

**Comment by dsajdak** [comment]
@chen5027 The software you reference requires agreeing to a license agreement which CCR staff are not permitted to do on behalf of research groups.  You or someone in your group would need to install this in your project directory.  Their list of supported operating systems doesn't include the one running on our compute nodes at this time (Ubuntu 24), which may be a problem getting this to run.  In addition to these issues, it requires conda which we do not support on our systems.  Please [see here](https://docs.ccr.buffalo.edu/en/latest/software/modules/#anaconda-python) for more info on that policy.  You might want to try using a container for this software as you can control the operating system and keep conda separate from our environment.  [See here](https://docs.ccr.buffalo.edu/en/latest/howto/containerization/) for our container documentation, if you're not already familiar with using containers on our systems.

There is an Easybuild recipe for software of the same name.  Though a few years out of date, if this is the same software but an open source version, we can attempt to install it for you.  Please [see here](https://github.com/Magdoll/Cogent) and let us know if this is what you're looking to use.  Thanks!

**Comment by chen5027** [comment]
Hello, Marianne

My lab has been experiencing issues analyzing the data generated from your
new kits, and we are trying everything possible to solve the problem.  One
possibility is that we did not trim the index properly, and now we are
trying to install your Cogent on our cluster to perform your exact
recommended analysis.  However, our computational people experienced such
license and compatibility issues and could you suggest whether there is any
method to bypass this license issue and could you suggest whether our
system is compatible with the software?

Thanks,

Dahong

**Comment by chen5027** [comment]
Dear Dahong,

I forwarded your email to Bioinformatics Specialist who will contact you.

Thank you very much for your patience.

Sincerely,
Marianne


Marianne Rivkin, Ph.D.
Technical Support Scientist II
Takara Bio USA, Inc
Phone: 800.662.2566 ext.2
***@***.***
