### ISSUE TITLE
SeuratData

### ISSUE THREAD

**Issue by chen5027** [ubccr/software-layer#411]
Could you install R v4.4 and the packages below?  Thanks!

library(Seurat)
library(SeuratData)
library(patchwork)
library(dplyr)

**Comment by chen5027** [comment]
Yes, Dori, please install them under v4.2.  I am afraid I don't have the
related expertise.

Thanks,

Dahong

**Comment by dsajdak** [comment]
@chen5027 These libraries have been added to the R/4.2.0 installation in `ccrsoft/2023.01`
