### ISSUE TITLE
GROMACS 2023.1

### ISSUE THREAD

**Issue by pkoduro** [ubccr/software-layer#46]
Dear CCR Support Team,

I am currently working on a project that requires the use of GPU-accelerated simulations with GROMACS. However, the version of GROMACS currently available on our system (2019.2) does not seem to fully support the newer generation GPUs we have at CCR.

I kindly request that a build of GROMACS version 2022.5 or newer version 2023 be made available on our system. This version is expected to have the necessary GPU support and will significantly enhance our research capabilities.

Please let me know if there are any additional details I can provide to facilitate the process.

Thank you for your attention to this matter.

Best regards,
Patrick

**Comment by al42and** [comment]
Please be advised that GROMACS 2022.6 was released today. It is recommended to use it over 2022.5 due to fixes for multi-GPU runs with GPU-aware MPI: https://manual.gromacs.org/2022.6/release-notes/2022/2022.6.html.

2023.2 will be released later this week.

**Comment by aebruno** [comment]
@pkoduro Apologies for the delay. GROMACS 2023.1 with CUDA support is now available. To use run:
```
module load foss 
module load gromacs/2023.1-CUDA-11.8.0
```

**Comment by pkoduro** [comment]
@aebruno 
Thank you very much! I appreciate it.
