### ISSUE TITLE
Boost librares for intel toolchain

### ISSUE THREAD

**Issue by aebruno** [ubccr/software-layer#49]
Build boost libraries for intel2022

**Comment by tonykew** [comment]
Every version of boost I can find, including the latest release version: 
    https://boostorg.jfrog.io/artifactory/main/release/1.83.0/source/boost_1_83_0.tar.bz2
fails to compile with Intel compilers e.g.

[...]/xmmintrin.h(1014): error: "__builtin_shuffle" is not supported
    return (__m128) __builtin_shuffle ((__v4sf)__A, (__v4sf)__B,

Intel's icc & clang do not support  __builtin_shuffle  as per:

https://community.intel.com/t5/Intel-C-Compiler/builtin-shuffle-GCC-compatibility-and-has-builtin/td-p/1143619
https://community.intel.com/t5/Intel-C-Compiler/Intel-compiler-doesn-t-support-builtin-shuffle/m-p/1128618

Code builds with the GCC toolchain, but not "intel-linux" insofar as I can tell

**Comment by tonykew** [comment]
The "__builtin_shuffle" error is due to icpc (and icc) using GNU gcc header files instead of the Intel supplied ones.
Andy is working on changing theIntel compiler wrappers to add the correct default -I include dirs.

**Comment by aebruno** [comment]
Boost 1.77.0 is now available for intel:
```
$ ml spider boost

-----------------------------------------------------------------------------------------------------------------------------------------------------------
  boost: boost/1.77.0
-----------------------------------------------------------------------------------------------------------------------------------------------------------
    Description:
      Boost provides free peer-reviewed portable C++ source libraries.

    Properties:
      Tools for development

    You will need to load all module(s) on any one of the lines below before the "boost/1.77.0" module is available to load.

      gcc/11.2.0
      intel-compilers/2022.0.1  impi/2021.5.0
```
