### ISSUE TITLE
Stata

### ISSUE THREAD

**Issue by guanjhenwu** [ubccr/software-layer#52]
Hi, 
May I kindly ask if you could please re-install Stata (https://www.stata.com/)? Thank you!

**Comment by jbednasz** [comment]
@guanjhenwu - I will be looking at your request to intstall Stata. Before I begin, I have a couple questions:
 - Do you still need this installed? 
 - What is your CCR username?
 - Have you started using the "new environment" at CCR? (https://docs.ccr.buffalo.edu/en/latest/howto/newenv/)
Thanks - Jon

**Comment by guanjhenwu** [comment]
Hi Jon,
 To answer your question, please see below:

   - Do you still need this installed? Yes!
   - What is your CCR username? guanjhen
   - Have you started using the "new environment" at CCR? Not yet!

Many thanks,
Jenny

On Mon, Sep 18, 2023 at 10:49 AM jbednasz ***@***.***> wrote:

> @guanjhenwu
> <https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fguanjhenwu&data=05%7C01%7Cguanjhen%40g-mail.buffalo.edu%7C6b24a678272d479f616d08dbb85672c7%7C96464a8af8ed40b199e25f6b50a20250%7C0%7C0%7C638306453665627182%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=N2sO1wJl8M%2BH4ortQxSaqrDwDQeSeWSV7l79f2gz0Ew%3D&reserved=0>
> - I will be looking at your request to intstall Stata. Before I begin, I
> have a couple questions:
>
>    - Do you still need this installed?
>    - What is your CCR username?
>    - Have you started using the "new environment" at CCR? (
>    https://docs.ccr.buffalo.edu/en/latest/howto/newenv/)
>    Thanks - Jon
>
> —
> Reply to this email directly, view it on GitHub
> <https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fubccr%2Fsoftware-layer%2Fissues%2F52%23issuecomment-1723601827&data=05%7C01%7Cguanjhen%40g-mail.buffalo.edu%7C6b24a678272d479f616d08dbb85672c7%7C96464a8af8ed40b199e25f6b50a20250%7C0%7C0%7C638306453665783398%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=yL3lN0fRotLQPBEGqd%2BzLaQ9O%2BNzT4aNstqZ0lC9N%2Bw%3D&reserved=0>,
> or unsubscribe
> <https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA77UKXH6O3YOBZB5AA3WKR3X3BNPFANCNFSM6AAAAAAZQ3KEDQ&data=05%7C01%7Cguanjhen%40g-mail.buffalo.edu%7C6b24a678272d479f616d08dbb85672c7%7C96464a8af8ed40b199e25f6b50a20250%7C0%7C0%7C638306453665783398%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zYSVQjcPTJByPb8cZCn%2BCeV3jPxuBU4h9rkwZ6li%2FMI%3D&reserved=0>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>


-- 
Guan-Jhen (Jenny) Wu
*PhD Student, Finance*
*University at Buffalo*
*School of Management*

**Comment by jbednasz** [comment]
@guanjhenwu - Thank you for your response. Before we get started on the build we would like you to get started in the new environment. Please see https://docs.ccr.buffalo.edu/en/latest/howto/newenv/ 
Once you are ready, I will start working on the build.

Thanks.

Jon

**Comment by drosch** [comment]
Hi Dori

You asked us to post here if we still need Stata on CCR. We do. We have at least wo project in which Stata on CCR will be helpful. Also, Stata is commonly used in Finance and other areas. I am sure the need to use Stata will come up again.

It would be great if you could help us to re-install it. Please let us know if you need anything from us.

Kind regards
Dominik (ccr: drosch)

**Comment by WansooChoi** [comment]
Hi Dori,

This is Wansoo, and Professor Dominik Roesch is my advisor.
I am also commenting here to let you know that we need Stata on CCR. 
My CCR id is wansooch.

Sincerely,
Wansoo

**Comment by dsajdak** [comment]
Because Stata is a license product, CCR will not be installing it in a central location.  If you have a license, we can provide instructions for using it on our systems.  Please contact [CCR Help](https://docs.ccr.buffalo.edu/en/latest/help/) for more information.
