### ISSUE TITLE
NAMD 2.14 with CUDA Support

### ISSUE THREAD

**Issue by pkoduro** [ubccr/software-layer#54]
Hi,

I would like to request the setup of NAMD 2.11 on our High-Performance Computing (HPC) system. Additionally, to leverage the capabilities of our HPC's GPU units, it would be highly beneficial if this build could include CUDA support.

The use of this software with CUDA capabilities will greatly enhance the speed and efficiency of my research work, and I believe it will be beneficial for other users in our community who are also involved in similar computational tasks.

I appreciate your time and effort in addressing this request. If you need any further information from me, please do not hesitate to ask.

Thank you for considering my request, and thank you.

Best regards,
Patrick

**Comment by dsajdak** [comment]
Hi @pkoduro Thanks for the request.  We have NAMD 2.14 currently installed and we're working on a build to utilize the GPUs.  For now, you can use this on the nodes in the reservation we gave you access to:

```
module spider namd
module load gcc/11.2.0  openmpi/4.1.1 namd/2.14-mpi
```

I'll leave this issue open until we have the GPU optimization built.

**Comment by pkoduro** [comment]
Dear @dsajdak

Thank you for your response. I'm currently utilizing NAMD 2.14 on the nodes provided in the reservation. I made the request primarily because I noticed the GPU wasn't being utilized, which is essential for my computations.

It's encouraging to hear that you are actively working on this. I appreciate your efforts and will patiently await the GPU-optimized build.

Thank you

**Comment by dsajdak** [comment]
@pkoduro sorry I knew that you were using that but forgot!

**Comment by pkoduro** [comment]
Hi @dsajdak 


Is there any progress made on the NAMD 2.14 build that supports CUDA? 

Thank you.

cc: @tdgrant1

**Comment by dsajdak** [comment]
@pkoduro Sorry for the delay but it is in progress.  This is one of the harder ones as you've probably already realized :)

**Comment by aebruno** [comment]
@pkoduro Apologies for the delay. NAMD 2.14 with CUDA support is now available. To use run:
```
module load foss 
module load namd/2.14-CUDA-11.8.0
```

**Comment by pkoduro** [comment]
@aebruno 
Thank you! I am grateful.
