### ISSUE TITLE
RepeatModeler and RepeatMasker

### ISSUE THREAD

**Issue by dmacguigan** [ubccr/software-layer#56]
Hello,

I would like to request the installation of RepeatModeler (https://github.com/Dfam-consortium/RepeatModeler, http://www.repeatmasker.org/RepeatModeler/) and RepeatMasker (https://www.repeatmasker.org/RepeatMasker/). I have tried to install this software myself, but have run into issues during configuration, particularly with the Perl dependencies. 

This software would be very useful for a number of labs in the Biological Sciences department. Masking repetitive elements in genomes is a crucial prerequisite for functional annotation and many other analyses.

Thanks,
Dan

**Comment by dmacguigan** [comment]
Hello Dori,

I will try using the Easy Build recipes for this software.

On another note, our lab has a considerable number of modules built using the old system (located in /projects/academic/tkrabben/modules_KrabLab/). Is there an easy way for us to switch these over to the new module system?

Best,
Dan

--
Dan MacGuigan, PhD
he-him-his
NSF Postdoctoral Fellow
Department of Biological Sciences
University at Buffalo
@DMacGuig
________________________________

**Comment by dsajdak** [comment]
HI @dmacguigan did you still need these installed by CCR or did you get them installed yourself?

**Comment by dmacguigan** [comment]
Hello Dori,

I was unable to install this software. EasyBuild does not have a RepeatModeler recipe that is compatible with the cluster's compiler toolchains. And while RepeatMasker has a foss-2020b recipe, the software version is slightly out of date and I was unable to build it successfully anyway.

If you are able to install the latest versions of this software, I'm sure my lab and others would use them.

Best,
Dan

--
Dan MacGuigan, PhD
he-him-his
NSF Postdoctoral Fellow
Department of Biological Sciences
University at Buffalo
https://danjmac.weebly.com/
Google Scholar<https://scholar.google.com/citations?user=ZfvNw2gAAAAJ&hl=en&authuser=1>
________________________________

**Comment by dsajdak** [comment]
@dmacguigan ok thanks for trying.  We'll give it a try as well!

**Comment by dsajdak** [comment]
Hi @dmacguigan SUCCESS!  RepeatModeler, RepeatMasker, and RepeatScout have been installed in the new software release.  Use `module spider repeat` to find them and any dependencies

**Comment by dmacguigan** [comment]
Hi Dori,

That's great, thank you!

I see that you were able to build the latest versions of both software. Did you make custom easyconfig files? If so, would you mind sharing them? I'm trying to learn the new module system, so seeing working examples would be helpful.

Best,
Dan

--
Dan MacGuigan, PhD
he-him-his
NSF Postdoctoral Fellow
Department of Biological Sciences
University at Buffalo
https://danjmac.weebly.com/
Google Scholar<https://scholar.google.com/citations?user=ZfvNw2gAAAAJ&hl=en&authuser=1>
________________________________

**Comment by dsajdak** [comment]
Yes, I actually meant to share that with you.  Some of them, I just had to change the GCC version from 11.3 to 11.2 but others needed some of the dependency versions changes and one had an issue with the sanity test passing.  You can see my recipes [here](#73 )
