### ISSUE TITLE
SAS

### ISSUE THREAD

**Issue by dsajdak** [ubccr/software-layer#58]
requested via ticket 33567

**Comment by dsajdak** [comment]
See also ticket #[35435](https://ubccr.freshdesk.com/a/tickets/35435)

**Comment by ANekhai** [comment]
I've started work on a SAS container. I'm converting the example SAS dockerfile to a Singularity definition file currently. Will post updates once the container is built!

**Comment by dsajdak** [comment]
SAS is available in a container.  Documentation on how to use it on CCR's systems can be found [here](https://docs.ccr.buffalo.edu/en/latest/software/modules/#sas)
