### ISSUE TITLE
The SRA Toolkit

### ISSUE THREAD

**Issue by BlessyBoby** [ubccr/software-layer#61]
https://github.com/ncbi/sra-tools/wiki/02.-Installing-SRA-Toolkit

SRA Toolkit for my RPCI Visualization Desktop

**Comment by dsajdak** [comment]
Hi @BlessyBoby these software build requests are for CCR's new environment which RPCI users are not yet a part of.  To make something available on the RPCI viz desktop you need to request that through RPCI IT support.  I'm pretty certain they already have this installed in their existing modules so they can just point you to that.
