### ISSUE TITLE
RStudio

### ISSUE THREAD

**Issue by dsajdak** [ubccr/software-layer#63]
Install Rstudio

**Comment by jebard** [comment]
Would LOVE to have RStudio available -- would help quite a bit for both lab use as well as for teaching 519 in the spring

**Comment by princesuklaroy** [comment]
RStudio will be really helpful to have on CCR.

**Comment by dsajdak** [comment]
This is on hold while we wait for the latest release.  There was a postgres requirement causing the build to fail but they've removed the requirement and are testing for their next production release.  We'll reattempt the install at that point.  [See here](https://github.com/rstudio/rstudio/issues/8968) for more info

**Comment by elpequeno** [comment]
The reported issue is resolved in [v2023.12.0+369](https://github.com/rstudio/rstudio/releases/tag/v2023.12.0%2B369) according to the RStudio github.

**Comment by dsajdak** [comment]
The Easybuild process is not working in our environment so we are investigating alternative options to support Rstudio.

**Comment by jebard** [comment]
Thanks for the update! Fingers crossed we can get it up and going. The BCH519 class where i was hoping to use RStudio on CCR is end of March, but understand if thats not feasible. Happy to help any way I can too!

**Comment by dsajdak** [comment]
Hello all!  RStudio Server has been published to ccrsoft/2023.01 and is now available in OnDemand.  Thanks for your patience while we sorted out the best way to provide this service.

**Comment by jebard** [comment]
That's the best news i've heard in weeks!!! Thanks CCR team :)
