### ISSUE TITLE
Request for installation  of pybedtools

### ISSUE THREAD

**Issue by mhalfon** [ubccr/software-layer#68]
We have a lot of things that use this wrapper, found here: https://pypi.org/project/pybedtools/ but at present no one computer-savvy enough to do the new module installs.
thanks.

**Comment by dsajdak** [comment]
Hi @mhalfon - this is all set!

```
vortex-future: module spider pybedtools

-----------------------------------------------------------------------------------------------------------------------------------------------------
  pybedtools: pybedtools/0.8.2
-----------------------------------------------------------------------------------------------------------------------------------------------------
    Description:
      pybedtools wraps and extends BEDTools and offers feature-level manipulations from within Python.


    You will need to load all module(s) on any one of the lines below before the "pybedtools/0.8.2" module is available to load.

      gcc/11.2.0

    Help:

      Description
      ===========
      pybedtools wraps and extends BEDTools and offers feature-level manipulations from within Python.


      More information
      ================
       - Homepage: https://daler.github.io/pybedtools
```

**Comment by mhalfon** [comment]
thanks!
m

> On Sep 22, 2023, at 1:47 PM, Dori Sajdak ***@***.***> wrote:
> 
> 
> Hi @mhalfon - this is all set!
> 
> vortex-future: module spider pybedtools
> 
> -----------------------------------------------------------------------------------------------------------------------------------------------------
>   pybedtools: pybedtools/0.8.2
> -----------------------------------------------------------------------------------------------------------------------------------------------------
>     Description:
>       pybedtools wraps and extends BEDTools and offers feature-level manipulations from within Python.
> 
> 
>     You will need to load all module(s) on any one of the lines below before the "pybedtools/0.8.2" module is available to load.
> 
>       gcc/11.2.0
> 
>     Help:
> 
>       Description
>       ===========
>       pybedtools wraps and extends BEDTools and offers feature-level manipulations from within Python.
> 
> 
>       More information
>       ================
>        - Homepage: https://daler.github.io/pybedtools
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.
> 

-----------------------------------
Marc S. Halfon, Ph.D.
Professor
Dept. of Biochemistry
Dept. of Biological Sciences
Dept. of Biomedical Informatics
University at Buffalo-SUNY

NY State Center of Excellence in Bioinformatics & Life Sciences

Molecular and Cellular Biology Department
Roswell Park Comprehensive Cancer Center

Room 5128
JSMBS, 955 Main St.
ph: (716) 829-3126
fax: (716) 849-6655
***@***.***
URL: http://halfonlab.ccr.buffalo.edu

mailing address:
Jacobs School of Medicine and Biomedical Sciences
University at Buffalo
955 Main St. 
Buffalo, NY 14203
