### ISSUE TITLE
SRA Toolkit

### ISSUE THREAD

**Issue by sssijjapu** [ubccr/software-layer#70]
Currently need to use SRA Toolkit in the UB_HPC Shell for students (new environment). Was told to request to have CCR staff install it into the shell.

**Comment by dsajdak** [comment]
HI @sssijjapu please separate these out as different issues as we're sharing the load of software installs across all of our staff.  FYI we can't always install the "latest" of software versions.  We go based on the EasyBuild recipes available at the time for the compiler toolchains we have in our environment.  We'll let you know what we're able to install for these different software packages.

**Comment by dsajdak** [comment]
We are unable to build SRA toolkit at this time.  There is a problem with the c code of one of the dependencies which we do not have the ability to override.  Many things were tried to work around this issue.  Sometimes this happens and with a newer version of either the EasyBuild recipe, the software package, or its dependencies the issue gets resolved and we can build successfully.  For now, this issue will be closed.
