### ISSUE TITLE
FAST QC

### ISSUE THREAD

**Issue by sssijjapu** [ubccr/software-layer#71]
Was wondering if FAST QC could be installed in the student shell (new environment). Need to perform quality control on RNA reads, so if there is a problem uploading FASTQC an alternative program can also work. I've attached a link [https://www.bioinformatics.babraham.ac.uk/projects/fastqc/](url)

**Comment by dsajdak** [comment]
Hi @sssijjapu FastQC has been installed on the cluster

```
vortex-future:~$ module spider fastqc

-----------------------------------------------------------------------------------------------------------------------------------------------------
  fastqc: fastqc/0.11.9-Java-11.0.16
-----------------------------------------------------------------------------------------------------------------------------------------------------
    Description:
      FastQC is a quality control application for high throughput sequence data. It reads in sequence data in a variety of formats and can either
      provide an interactive application to review the results of several different QC checks, or create an HTML based report which can be
      integrated into a pipeline.

    Properties:
      Bioinformatic libraries/apps

    This module can be loaded directly: module load fastqc/0.11.9-Java-11.0.16

    Help:

      Description
      ===========
      FastQC is a quality control application for high throughput
      sequence data. It reads in sequence data in a variety of formats and can either
      provide an interactive application to review the results of several different
      QC checks, or create an HTML based report which can be integrated into a
      pipeline.


      More information
      ================
       - Homepage: https://www.bioinformatics.babraham.ac.uk/projects/fastqc/

```

**Comment by chen5027** [comment]
Could you solve this problem?

@cpn-q08-31-02:$ module load fastqc/0.11.9-Java-11.0.16
dahongch@cpn-q08-31-02:$ fastqc
Exception in thread "main" java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:208)
        at java.desktop/java.awt.Window.<init>(Window.java:548)
        at java.desktop/java.awt.Frame.<init>(Frame.java:423)
        at java.desktop/java.awt.Frame.<init>(Frame.java:388)
        at java.desktop/javax.swing.JFrame.<init>(JFrame.java:180)
        at uk.ac.babraham.FastQC.FastQCApplication.<init>(FastQCApplication.java:63)
        at uk.ac.babraham.FastQC.FastQCApplication.main(FastQCApplication.java:338)
