### ISSUE TITLE
CutAdapt and FASTQCScreen

### ISSUE THREAD

**Issue by sssijjapu** [ubccr/software-layer#76]
Hi! I will need FASTQCScreen and CutAdapt uploaded to the UB_HPC Shell.

**Comment by dsajdak** [comment]
@sssijjapu are you referring to FastQ-Screen?  https://www.bioinformatics.babraham.ac.uk/projects/fastq_screen/

Also, in the future please enter individual build requests for software and include a reference so we can make sure we're installing the correct one.  There are so many open source projects named the same or similarly.  Thanks!

**Comment by sssijjapu** [comment]
Good afternoon, so sorry for the late reply. Yes, I was referring to Fast-Q Screen (used to detect contamination). I attached a link to the program. So sorry, but I'm not sure what an individual build request is. Are you referring to creating a new ticket on GitHub? I'm relatively new to this stuff, so still getting familiarized.
________________________________

**Comment by dsajdak** [comment]
@sssijjapu CutAdapt is now deployed to CCR's software repository.  I'm having issues with a dependency for Fast-Q screen but am still working on it.  Yes, we're just asking for a separate GitHub issue for each software package as we share the load of these installs among all staff members.  Thanks!

**Comment by dsajdak** [comment]
@sssijjapu FastQ_Screen has been installed
