### ISSUE TITLE
pdftk

### ISSUE THREAD

**Issue by ngmaclaren** [ubccr/software-layer#88]
Hi! Could you please install the software package [pdftk](https://www.pdflabs.com/)?

**Comment by aebruno** [comment]
hi @ngmaclaren, curious is pdftk a hard requirement for you? What are you looking to do with PDFs?

**Comment by ngmaclaren** [comment]
No, it's not a hard requirement. I tend to make figures of simulation results as PDFs, so it is easier to move them around, view them, etc, if I can gather them up into one document. Without pdftk on the cluster I can tar the files and use pdftk on my own machine. It would be more convenient if pdftk were present on the cluster---that's all.

**Comment by aebruno** [comment]
@ngmaclaren Sounds good. Thanks for following up. pdftk requires gcj which has been removed from GCC as of version 7. We currently support GCC 11.2.0 so it doesn't look like we'll be able to easily install this for you unfortunately. Depending on what you need we can possibly suggest alternative PDF manipulation tools.

I'll go ahead and close this for issue for now and we can always revisit this in the future.
