### ISSUE TITLE
Launcher

### ISSUE THREAD

**Issue by cli110** [ubccr/software-layer#89]
Launcher is a framework for running large collections of serial or multithreaded applications known as High Throughput Computing (HTC), as a single multinode parallel job on batch-scheduled High Performance Computing (HPC) systems. Launcher can be used to perform simple, data parallel, high throughput computing (HTC) workflows on clusters, massively parallel processor (MPP) systems, workgroups of computers, and personal machines.
https://docs.tacc.utexas.edu/software/launcher/

**Comment by dsajdak** [comment]
@cli110 We discussed this in our staff meeting and we're not going to be able to install this.  There is no Easybuild recipe and we can not devote the time to creating one at this time.  It is something you can install yourself in your home or project directory, if you'd like.  Instructions can be found  here: https://github.com/TACC/launcher
