### ISSUE TITLE
CDO

### ISSUE THREAD

**Issue by rljbufny1** [ubccr/software-layer#90]
The Ghub netcdfregrid tool currently loads module cdo/1.7.1. 
Please install cdo in the new ccr environment.

I rechecked an email that Dori Sajdak sent us and her recommendation is to install cdo with the CDO-2.0.5-gompi-2021b.eb 
EasyBuild recipe.

I can test the netcdfregrid code with this version of cdo first after it is installed.

**Comment by aebruno** [comment]
@rljbufny1 CDO is now available. To use run: `module load gompi cdo`
