### ISSUE TITLE
VASP

### ISSUE THREAD

**Issue by animeshd98** [ubccr/software-layer#92]
Hi,

I am Animesh, PhD student in Dr.Singisetti's Lab in the Department of Electrical Engineering. I talked with Dori regarding using VASP on the new environment. VASP is a licensed software and we have a purchased license for it.  A previous graduate student from our group worked with CCR to install VASP on the old software environment. But I am having issues installing VASP on the new environment.  Is it possible for you to build VASP for us in the new environment?

**Comment by tonykew** [comment]
Dear Animesh,

The version of VASP in Dr.Singisetti's /projects dir is 6.1.2

    /projects/academic/uttamsin/VASP6.1.2/vasp.6.1.2.tgz

Is this the version you want to use?
There are newer versions available for download from the VASP website:

    https://www.vasp.at

Based on the FAQ https://www.vasp.at/info/faq/

    "The passwords [for the portal, from which you can download the software] are sent to ONE person
     per group (the group leader) without exception, and must mot be given to anyone else."

I would imagine that Dr.Singisetti has the account information to download a
newer version.  Looking at the forum that appears to be version 6.4.2 but I cannot
verify this.

**Comment by tonykew** [comment]
Animesh installed VASP 6.4.2 in their projects directory - closing the request.
