### ISSUE TITLE
Problems With the Command Module Load in Batch Test

### ISSUE THREAD

**Issue by sssijjapu** [ubccr/software-layer#97]
I'm unable to submit a complete job to align RNA reads using Bowtie2. The job is able to submit, however, the output script says the module load command is not found. I've attached the text file for the batch test, and the output script. When my PI runs the same job in the faculty cluster; the command for module is identified and able to run Bowtie. Does the module command in the new environment UB_HPC Cluster Shell need to be updated. I am able to use the command module on a single line. 

Text File
<img width="1440" alt="TextFile_Error" src="https://github.com/ubccr/software-layer/assets/146007596/362ff43e-3b55-418d-8cce-649c46de7c06">

Output Script
<img width="1432" alt="Output Script " src="https://github.com/ubccr/software-layer/assets/146007596/fd0b65ef-bd5c-420b-a0c0-ae35c81f2c65">

**Comment by aebruno** [comment]
@sssijjapu Please submit a ccr-help support ticket. These issues are for build requests only.
