### ISSUE TITLE
Quantum Espresso v6.2

### ISSUE THREAD

**Issue by nishagen** [ubccr/software-layer#98]
Hi,

My name is Nisha Geng and I work in Dr. Eva Zurek group, from the chemistry department. Almost everyone in my group used Quantum Espresso so I'd like to submit a request for the Quantum Espresso installation for the new module (it is free). In addition, I was wondering that can you install the older version of QE as well (6.2)? 

Thanks for the support,

Nisha

**Comment by dsajdak** [comment]
Hi @nishagen!  We do have Quantum Espresso 7.1 installed.  You can find it with the 'module spider' command and see what dependencies are required to load first:

```
$ module spider quantum

-----------------------------------------------------------------------------------------------------------------------------------------------------
  quantumespresso: quantumespresso/7.1
-----------------------------------------------------------------------------------------------------------------------------------------------------
    Description:
      Quantum ESPRESSO is an integrated suite of computer codes for electronic-structure calculations and materials modeling at the nanoscale. It is
      based on density-functional theory, plane waves, and pseudopotentials (both norm-conserving and ultrasoft).

    Properties:
      Chemistry libraries/apps

    You will need to load all module(s) on any one of the lines below before the "quantumespresso/7.1" module is available to load.

      gcc/11.2.0  openmpi/4.1.1
```
and then load it with:

`module load gcc/11.2.0  openmpi/4.1.1 quantumespresso/7.1`  

Is there a reason you need an older version?

**Comment by nishagen** [comment]
Dear Dori Sajdak,

I requested QE 6.2 since several of my old on-going projects were
calculated by QE6.2 and they are unpublished yet. I want to make sure my
data is consistent. In addition, the new version of QE 7.1 might have some
bugs. I have encounter the bugs when I used qe 6.4 and I am not sure if
they solved it in the latest version.

Best,
Nisha

**Comment by dsajdak** [comment]
@nishagen We discussed in our staff meeting and we are not going to install this older version.  You are welcome to install this in your group's project space.
