### ISSUE TITLE
OpenMolcas parallel version 

### ISSUE THREAD

**Issue by asmitase** [ubccr/software-layer#99]
Hello,
I am Asmita Sen (username: asmitase) from Prof. Jochen Autschbach group, Department of Chemistry, a new CCR user. I want to install OpenMolcas software (**parallel version**) locally inside my account. The path for the installation will be "/projects/academic/jochena/asmitase/molcas_parallel". I am requesting here the CCR to install these software in my home directory. 

Thanks and regards,
Asmita

**Comment by aebruno** [comment]
This is all set: 
```$ module load intel openmolcas```
